JE AI FAIT CAMPAGNE AVEC MON CHEF PARCE QUE JE CROYAIS À CELA . 
CETTE LETTRE REPREND ESSENTIELLEMENT CE QUE ON A DANS LA PLATEFORME ÉLECTORALE . 
LE PROCESSUS DE CALGARY EST UN PROCESSUS QUI VA , ESPÉRONS - LE , ÉVOLUER . 
SUR LES DÉCLARATIONS QUE LE DÉPUTÉ DE LE BLOC A CITÉES PAR RAPPORT À MON CHEF , OUI JE SUIS DE ACCORD . 
SI ON POUVAIT APPLIQUER LES POINTS QUE LE DÉPUTÉ A CITÉS RELATIVEMENT À LE DÉPUTÉ DE SHERBROOKE , JE PENSE QUE LE PAYS IRAIT PEUT - ÊTRE MIEUX . 
LE DÉPUTÉ BLOQUISTE SAIT TRÈS BIEN QUE LA POSITION DE MON CHEF , LA POSITION DE LE PARTI CONSERVATEUR À LE QUÉBEC EST UNE DE LES POSITIONS LES PLUS POPULAIRES ET QUI EST EN MESURE DE RASSEMBLER LE ENSEMBLE DE LES QUÉBÉCOIS ET DE LES QUÉBÉCOISES . 
ÇA , LE DÉPUTÉ BLOQUISTE LE SAIT , ET CE EST POUR ÇA QUE ILS NE VEULENT PAS QUE ON PRENNE TROP DE POUVOIR À LE QUÉBEC PARCE QUE ILS SAVENT QUE ILS VONT DÉBARQUER LA PROCHAINE FOIS . 
M . RICK BOROTSIK ( BRANDON - SOURIS , PC ) : 
MONSIEUR LE PRÉSIDENT , JE VOUDRAIS REMERCIER MON COLLÈGUE DE LE QUÉBEC DE AVOIR ACCEPTÉ DE PARTAGER SON TEMPS AVEC UN COLLÈGUE DE LE OUEST DE LE CANADA À LE OCCASION DE CE DÉBAT DE UNE IMPORTANCE PRIMORDIALE POUR LE PAYS . 
JE SUIS HEUREUX DE ÊTRE À LA CHAMBRE POUR VOIR LA DERNIÈRE MÉTAMORPHOSE DE LE PARTI RÉFORMISTE , LE PASSAGE DE LE COCON À LE PAPILLON . 
IL NOUS PRÉSENTE MAINTENANT SA POSITION SUR LE UNITÉ NATIONALE . 
IL NE Y A GUÈRE QUE SIX MOIS , LA POSITION PRISE À LE ÉGARD DE LE UNITÉ NATIONALE PAR MES COLLÈGUES DE LE PARTI RÉFORMISTE ÉTAIT LOIN DE ÊTRE AUSSI POSITIVE QUE LA POSITION EXPOSÉE À LA CHAMBRE AUJOURD' HUI . 
JE NE DÉVOILE PAS UN SECRET EN DISANT QUE LE PARTI PROGRESSISTE - CONSERVATEUR CROIT FORTEMENT À LA FÉDÉRATION CANADIENNE . 
IL CROIT FERMEMENT À LE EXISTENCE DE DIX PROVINCES ET DE DEUX TERRITOIRES . 
IL CROIT SINCÈREMENT QUE IL EST POSSIBLE DE ÊTRE EN FAVEUR DE LA FÉDÉRATION ET DE FAIRE EN SORTE QUE LE ON AIT DIX PROVINCES FORTES ET DEUX TERRITOIRES FORTS . 
JE PEUX MENTIONNER À CET ÉGARD LE EXPÉRIENCE ET LA CONFIANCE DE LE CHEF DE NOTRE PARTI . 
CE EST LE CHEF DE LE PARTI PROGRESSISTE - CONSERVATEUR QUI NOUS A SAUVÉ DE LE ABÎME . 
CE EST LUI QUI EST INTERVENU LORS DE LE DERNIER RÉFÉRENDUM PARCE QUE LE GOUVERNEMENT LIBÉRAL NE ASSURAIT PAS LA DIRECTION . 
CE EST À LUI QUE LE ON A DEMANDÉ DE FAIRE EN SORTE QUE LE PAYS RESTE UNI . 
IL Y A UNE MAJORITÉ DE QUÉBÉCOIS QUI VEULENT RESTER CANADIENS , ET ILS LE RESTERONT . 
LA POLITIQUE DE LE PARTI PROGRESSISTE - CONSERVATEUR A TOUJOURS REPOSÉ SUR LA CONSULTATION , LA CONCILIATION ET LA COMPRÉHENSION , CONTRAIREMENT À CELLE DE LE PARTI RÉFORMISTE . 
LA DÉCLARATION DE CALGARY A ÉTÉ APPROUVÉE ET ACCEPTÉE PAR LE PARTI PROGRESSISTE - CONSERVATEUR . 
IL EST BON DE VOIR QUE IL EXISTE UN LEADERSHIP AUTRE QUE CELUI DE LE GOUVERNEMENT LIBÉRAL FÉDÉRAL , LEQUEL EST PLUTÔT INSIGNIFIANT . 
LES PREMIERS MINISTRES PROVINCIAUX SE SONT ENTENDUS POUR PRÉSENTER UN PLAN , LA DÉCLARATION DE CALGARY . 
ILS ONT DÉCLARÉ QUE CETTE QUESTION ÉTAIT DE UNE IMPORTANCE TELLE QUE IL FALLAIT LA RÉSOUDRE SANS LE LEADERSHIP DE LE GOUVERNEMENT FÉDÉRAL . 
JE RENDS HOMMAGE À LA DÉCLARATION DE CALGARY , QUE NOUS APPROUVONS , ET JE REMERCIE LES PREMIERS MINISTRES . 
JE VAIS PARLER DE LA TRANSFORMATION DE LE PARTI RÉFORMISTE . 
IL NE Y A GUÈRE QUE SIX MOIS , PENDANT LA CAMPAGNE ÉLECTORALE , LES RÉFORMISTES DISAIENT EMPHATIQUEMENT QUE LES QUÉBÉCOIS NE SAVAIENT PAS COMMENT RÉSOUDRE LA CRISE DE LE UNITÉ . 
JE AIMERAIS SAVOIR QUELLE MOTIVATION CACHE CETTE MOTION . 
JE VOUDRAIS ÉGALEMENT DISCUTER DE LES NOTIONS DE SOCIÉTÉ DISTINCTE ET DE SOCIÉTÉ UNIQUE . 
SOUDAINEMENT , IL SEMBLE QUE LES RÉFORMISTES AIENT SUBI CETTE TRANSFORMATION MERVEILLEUSE ET PUISSENT ACCEPTER LA NOTION DE SOCIÉTÉ UNIQUE . 
JE AI COMBATTU DANS LES TRANCHÉES LORS DE LA DERNIÈRE CAMPAGNE ÉLECTORALE ET JE PUIS DIRE QUE LA NOTION DE SOCIÉTÉ DISTINCTE CONSTITUAIT UN ENJEU IMPORTANT . 
IL SE AGISSAIT DE UN ENJEU QUE LES RÉFORMISTES ONT UTILISÉ COMME RUSE POLITIQUE MESQUINE POUR TOUCHER DE LES CORDES SENSIBLES DANS LE OUEST DE LE CANADA . 
JE VOUDRAIS RAPPELER À LA CHAMBRE LES MOTIFS ... 
UNE VOIX : 
LE AVEZ - VOUS APPUYÉE ? 
M . RICK BOROTSIK : 
OUI , JE AI APPUYÉ LA NOTION DE SOCIÉTÉ DISTINCTE ET JE LE APPUIE ACTUELLEMENT . 
EN FAIT , LE QUÉBEC EST DISTINCT . 
IL EST TRÈS DISTINCT ET TRÈS UNIQUE , COMME TOUTES LES PROVINCES SONT TRÈS DISTINCTES ET TRÈS UNIQUES . 
ELLES NE ONT AUCUN POUVOIR SPÉCIAL , MAIS ELLES SONT NÉANMOINS DISTINCTES . 
NOUS ACCEPTONS LE BILINGUISME . 
NOUS ACCEPTONS LE FAIT QUE LA LANGUE EST DIFFÉRENTE À LE QUÉBEC . 
NOUS ACCEPTONS LE CARACTÈRE DISTINCTIF DE LE QUÉBEC . 
JE VOUDRAIS PORTER À LE ATTENTION DE LA CHAMBRE UNE CAMPAGNE PUBLICITAIRE UTILISÉE LORS DE LES DERNIÈRES ÉLECTIONS . 
CETTE CAMPAGNE VIENT DE LE MÊME PARTI QUI VEUT MAINTENANT CONSULTER LES QUÉBÉCOIS À LE SUJET DE LES TYPES DE DIRIGEANTS QUE NOUS DEVRIONS AVOIR DANS NOTRE PAYS . 
JE NE LE CROIS PAS . 
JE NE CROIS PAS À LES MOTIFS DE LE PARTI RÉFORMISTE . 
JE AI DE SÉRIEUSES PRÉOCCUPATIONS À LEUR SUJET . 
EN FAIT , UN EMPLOYÉ DE HAUT NIVEAU DE LE PARTI RÉFORMISTE A PUBLIÉ DANS LE NUMÉRO DE LE 30 OCTOBRE DE LE SUN DE CALGARY DIX RÉSOLUTIONS , DONT UNE DISAIT : « ÉLIMINEZ LE BILINGUISME ET LE BICULTURALISME . 
AVEC LA SÉPARATION DE LE QUÉBEC , LE BILINGUISME ET LE MULTICULTURALISME NE AURONT PLUS LEUR RAISON DE ÊTRE . » 
SELON MOI , CELA NE A RIEN DE UNE RÉSOLUTION PRÉSENTÉE EN VUE DE UNE CONSULTATION ... 
M . JASON KENNEY ( CALGARY - SUD - EST , RÉF . ) : 
MONSIEUR LE PRÉSIDENT , JE INVOQUE LE RÈGLEMENT . 
LE DÉPUTÉ A CITÉ UN EXTRAIT DE UN ARTICLE DATÉ DE LE 30 OCTOBRE . 
JE ME DEMANDE SE IL POURRAIT DONNER LE ANNÉE ET DÉPOSER LE DOCUMENT . 
LE VICE - PRÉSIDENT : 
M . RICK BOROTSIK : 
MONSIEUR LE PRÉSIDENT , JE ME RÉJOUIRAIS DE TRANSMETTRE CE DOCUMENT À LE DÉPUTÉ . 
IL SE AGIT DE UN ARTICLE DE LE SUN DE CALGARY EN DATE DE LE 30 OCTOBRE 1995 . 
M . JASON KENNEY : 
OH , TRÈS BIEN . 
M . RICK BOROTSIK : 
JE VOIS . 
LES CHOSES ONT BEAUCOUP CHANGÉ DEPUIS 1995 . 
JE CRAINS QUE LES INTENTIONS NE SOIENT PAS ACCEPTABLES POUR LE PARTI PROGRESSISTE CONSERVATEUR ET NOS DÉPUTÉS NE APPUIERONT PAS LA MOTION PRÉSENTÉE PAR LE PARTI RÉFORMISTE . 
M . JASON KENNEY ( CALGARY - SUD - EST , RÉF . ) : 
MONSIEUR LE PRÉSIDENT , JE TROUVE MALHEUREUX QUE LE CAUCUS CONSERVATEUR , CONTRAIREMENT À LE PARTI LIBÉRAL ET À LE NOUVEAU PARTI DÉMOCRATIQUE , NE VEUILLE PAS COLLABORER DANS UNE INITIATIVE DE CE GENRE . 
IL ME SEMBLE QUE LES CONSERVATEURS SE UNISSENT UNE FOIS DE PLUS À LEURS ANCIENS ALLIÉS SÉPARATISTES , AVEC DE LES GENS COMME LUCIEN BOUCHARD , QUI LES ONT GARDÉS À LE POUVOIR PENDANT NEUF ANS . 
SI LE PARTI CONSERVATEUR EST FAVORABLE À LE UNITÉ NATIONALE , POURQUOI Y A IL EU DE LES MEMBRES EN RÈGLE DE LE PARTI QUÉBÉCOIS QUI SE SONT PRÉSENTÉS SOUS SA BANNIÈRE LORS DE LES DERNIÈRES ÉLECTIONS FÉDÉRALES ? 
EST - CE LÀ UNE INDICATION DE SON DEGRÉ DE ENGAGEMENT ? 
SI LE CHEF DE LE PARTI CONSERVATEUR EST LE GRAND HÉROS DE LE DERNIER RÉFÉRENDUM , POURQUOI SA PROPRE CIRCONSCRIPTION A ELLE PENCHÉ DE LE CÔTÉ DE LE OUI LORS DE LE DERNIER RÉFÉRENDUM ? 
À QUOI LE DÉPUTÉ SE OPPOSE IL ? 
LA PUBLICITÉ À LAQUELLE IL A FAIT ALLUSION DISAIT QUE IL ÉTAIT TEMPS QUE TOUS LES CANADIENS FASSENT ENTENDRE LEUR VOIX DANS LE DÉBAT SUR LE UNITÉ NATIONALE . 
CE EST EXACTEMENT CE QUE NOUS DEMANDONS AUJOURD' HUI . 
EN SE OPPOSANT À LA MOTION , LES CONSERVATEURS SE OPPOSENT - ILS À LE IDÉE DE DONNER UNE VOIX À TOUS LES CANADIENS DANS LE DÉBAT ? 
SONT - ILS HEUREUX QUE LE ANCIEN CONSERVATEUR BOUCHARD ET SON GOUVERNEMENT NE AIENT PAS VOULU DONNER À LES QUÉBÉCOIS LA POSSIBILITÉ DE SE EXPRIMER SUR LA QUESTION ? 
POURQUOI NE PAS LAISSER LES QUÉBÉCOIS SE EXPRIMER SUR LA DÉCLARATION DE CALGARY ? 
LE DÉPUTÉ NE COMPREND - IL PAS QUE LA CLAUSE DE CETTE DÉCLARATION SUR LES CARACTÉRISTIQUES UNIQUES NE A AUCUNE VALEUR JURIDIQUE , QUE ELLE NE EST PAS UNE CLAUSE DE INTERPRÉTATION , QUE ELLE EST ENCADRÉE PAR LES DISPOSITIONS SUR LE ÉGALITÉ QUI PARSÈMENT LE TEXTE ET QUI ÉTAIENT SINGULIÈREMENT ABSENTES DE LES ACCORDS DE CHARLOTTETOWN ET DE MEECH QUE LE GOUVERNEMENT MULRONEY A TENTÉ SANS SUCCÈS DE IMPOSER À LE PEUPLE ? 
M . RICK BOROTSIK : 
MONSIEUR LE PRÉSIDENT , ENCORE UNE FOIS , LES PROPOS PARTISANS DE LE DÉPUTÉ DE CALGARY SUD - EST SONT ASSEZ AGRÉABLES À ENTENDRE . 
NUL DOUTE QUE LE DÉPUTÉ SE REND COMPTE QUE , DE LE POINT DE VUE DE LE UNITÉ NATIONALE , LE GOUVERNEMENT PROGRESSISTE CONSERVATEUR COMPRENAIT BIEN MIEUX LES AFFAIRES DE LE QUÉBEC QUE NE LE FAIT LE PARTI RÉFORMISTE . 
EN CE QUI CONCERNE LA CONSULTATION , NOUS AVONS TOUJOURS DIT QUE LE PROCESSUS DE CONSULTATION EST LA CLÉ POUR RAMENER LES QUÉBÉCOIS DANS LE GIRON DE LA FÉDÉRATION CANADIENNE . 
AUCUNE PROVINCE NE EST PLUS ÉGALE QUE UNE AUTRE . 
NOUS RECONNAISSONS DANS NOS PRINCIPES DIRECTEURS QUE TOUTES LES PROVINCES DOIVENT TRAVAILLER ENSEMBLE AFIN DE RENFORCER LA FÉDÉRATION . 
NOUS CROYONS FERMEMENT À CE PROCESSUS . 
NOUS NE CROYONS PAS À LES FACTEURS DE DIVISION . 
M . PETER GOLDRING ( EDMONTON - EST , RÉF . ) : 
MONSIEUR LE PRÉSIDENT , JE PARTAGERAI MON TEMPS DE PAROLE AVEC MON COLLÈGUE , LE DÉPUTÉ DE PRINCE GEORGE - BULKLEY VALLEY . 
JE SUIS HEUREUX DE PRENDRE LA PAROLE POUR DIRE QUE JE APPUIE LA DÉCLARATION DE CALGARY , QUI CONSTITUE LE CADRE DE DISCUSSION SUR LE UNITÉ NATIONALE . 
BIEN DE LES CHOSES SE SONT PASSÉES DEPUIS LE RÉFÉRENDUM IL Y A DEUX ANS . 
IL Y A DEUX ANS , À LE MOMENT DE LE RÉFÉRENDUM , ON NOUS A DEMANDÉ DE NE PAS INTERVENIR DANS LA CAMPAGNE RÉFÉRENDAIRE . 
JE ME RÉJOUIS DE AVOIR LE OCCASION AUJOURD' HUI DE INTERVENIR SUR CETTE IMPORTANTE MOTION , ET CE , POUR DEUX RAISONS . 
DE ABORD , JE VEUX PRÉCISER QUE MES ÉLECTEURS ET MOI SOMMES EN FAVEUR DE LE MAINTIEN DE UN CANADA FORT ET UNI OÙ LES QUÉBÉCOIS ET TOUS LES AUTRES CANADIENS SE SENTENT CHEZ EUX . 
ENSUITE , JE VOUDRAIS INVITER LE GOUVERNEMENT À FAIRE PREUVE DE UN PEU DE HUMILITÉ . 
POURQUOI ? 
POUR UNE RAISON FORT SIMPLE . 
SI NOTRE PAYS DOIT ÊTRE SAUVÉ , CE NE SERA PAS GRÂCE À LE GOUVERNEMENT . 
CE NE SERA PAS GRÂCE À LES PLANS DE LE PREMIER MINISTRE NI À LES LETTRES DE LE MINISTRE DE LES AFFAIRES INTERGOUVERNEMENTALES NI À LES STRATÉGIES DE LES FONCTIONNAIRES QUI , IL Y A QUELQUES ANNÉES À PEINE , ONT ÉTÉ LES ARCHITECTES DE LE ACCORD DE CHARLOTTETOWN . 
PLUS TÔT LE GOUVERNEMENT ACCEPTERA UN PEU DE HUMILITÉ , PLUS TÔT LE VRAI TRAVAIL POURRA COMMENCER . 
CE SERA LES CANADIENS QUI SAUVERONT LE CANADA , LES HOMMES ET LES FEMMES QUI AIMENT CE PAYS ET QUI EN ASSURENT LA SURVIE CHAQUE JOUR PAR LEUR TRAVAIL ET LEUR CONFIANCE ; LES 150 000 PERSONNES QUI SE SONT RENDUES À MONTRÉAL DURANT LA CAMPAGNE RÉFÉRENDAIRE AFIN DE EXPRIMER LEUR AMOUR POUR LEUR PAYS ; ET LES MILLIONS DE CANADIENS À LA MAISON QUI ONT RETENU LEUR SOUFFLE DURANT LE VOTE . 
LE UNITÉ CANADIENNE A TOUCHÉ LE FOND DE LE ABÎME CE JOUR - LÀ . 
COMME JE LE AI DÉJÀ DIT DANS LE PASSÉ , AVEC DE LA VOLONTÉ ET DE LA DÉTERMINATION , LES CANADIENS PEUVENT RÉSOUDRE LES PROBLÈMES FÉDÉRAUX ET PROVINCIAUX . 
ILS PEUVENT RÉSOUDRE LES PROBLÈMES DE LES AUTOCHTONES . 
ILS PEUVENT RÉSOUDRE LES PROBLÈMES LINGUISTIQUES . 
CE SERA UNE EXPRESSION DE LA VOLONTÉ POPULAIRE QUI FERA LA DIFFÉRENCE , ET NON UN PLAN DIRECTEUR FONDÉ SUR DE LES MANIPULATIONS POLITIQUES . 
CE EST LA POPULATION QUI AURA LE DERNIER MOT . 
CE EST UNE LEÇON QUE LES NEUF PREMIERS MINISTRES PROVINCIAUX ET LES DEUX LEADERS TERRITORIAUX ONT PRIS À COEUR IL Y A TROIS MOIS LORSQUE ILS ONT RÉDIGÉ LA DÉCLARATION DE CALGARY . 
CHAQUE PROVINCE ET TERRITOIRE , SAUF LE QUÉBEC , A MIS EN PLACE UN MÉCANISME DE CONSULTATION AFIN QUE SES CITOYENS PUISSENT AVOIR VOIX À LE CHAPITRE SUR LES PRINCIPES DE LA DÉCLARATION DE CALGARY ET LE AVENIR DE LEUR PAYS . 
CE EST UNE ÉTAPE TRÈS IMPORTANTE . 
CETTE MOTION NOUS PERMET DE EXHORTER LA CHAMBRE À APPUYER CES EFFORTS POUR ENCOURAGER LA CONSULTATION . 
EN TANT QUE PARLEMENTAIRES , NOUS DEVONS ENCOURAGER NOS ÉLECTEURS À PARTICIPER À LES PROCESSUS DE CONSULTATION ÉTABLIS PAR LES PROVINCES . 
LA DÉCLARATION DE CALGARY PRÉSENTE CERTAINS AVANTAGES PAR RAPPORT À LES TENTATIVES PRÉCÉDENTES DE RENOUVELLEMENT DE LA FÉDÉRATION . 
NOUS DEVRIONS NOUS EFFORCER DE EN ASSURER LE SUCCÈS . 
ELLE A LE AVANTAGE DE VENIR DE LES PREMIERS MINISTRES PROVINCIAUX ET NON DE OTTAWA , CE QUI LUI DONNE PLUS DE CRÉDIBILITÉ À LES YEUX DE NOMBREUX CANADIENS QUI SE SOUVIENNENT DE LE FÉDÉRALISME EXÉCUTIF DESCENDANT QUI A PRODUIT LE ACCORD DE LE LAC MEECH ET LE ACCORD DE CHARLOTTETOWN . 
LES CANADIENS POURRONT PARTICIPER DIRECTEMENT À LES DISCUSSIONS . 
ELLE A LE AVANTAGE DE NE PAS ÊTRE UN FAIT ACCOMPLI . 
ELLE MONTRE PLUTÔT LA FLEXIBILITÉ DE LE RÉGIME FÉDÉRAL OÙ LES PROVINCES SONT LIBRES DE EXERCER LEURS POUVOIRS DE LA FAÇON QUI REFLÈTE LE MIEUX LEURS TRADITIONS ET LEUR CARACTÈRE . 
JE AI EU LE PLAISIR DE PARTICIPER À UNE ASSEMBLÉE PUBLIQUE LOCALE ORGANISÉE CONJOINTEMENT PAR MES COLLÈGUES PROVINCIAUX ÉLUS . 
LES DÉBATS DE NOTRE FORUM DE DISCUSSION PUBLIQUE ONT PORTÉ SUR DE NOMBREUX SUJETS , MAIS ONT ENCOURAGÉ ÉGALEMENT TOUT LE MONDE À FAIRE CONNAÎTRE LEURS IDÉES ET LEURS SUGGESTIONS À LE ASSEMBLÉE LÉGISLATIVE ALBERTAINE . 
LA DÉCLARATION PROPOSE À LA RÉFLEXION UN MOYEN DE BRISER LE IMPASSE QUE LE EXPRESSION « SOCIÉTÉ DISTINCTE » A CRÉÉE , À TORT OU À RAISON , EN POLARISANT LE OPINION SUR LA QUESTION DE SAVOIR SI LE QUÉBEC DEVRAIT AVOIR UN STATUT SPÉCIAL À LE SEIN DE LA CONFÉDÉRATION . 
LE CONCEPT DE SOCIÉTÉ DISTINCTE NE ÉTAIT PAS DÉFINI . 
CELUI DE CARACTÈRE UNIQUE EST COMPATIBLE AVEC LE PRINCIPE DE ÉGALITÉ . 
LA DÉCLARATION DE CALGARY RECONNAÎT LE CARACTÈRE UNIQUE DE LA SOCIÉTÉ QUÉBÉCOISE , CONSTITUÉE NOTAMMENT DE SA MAJORITÉ FRANCOPHONE , DE SA CULTURE ET DE SA TRADITION DE DROIT CIVIL , DE MÊME QUE LE RÔLE QUE LE GOUVERNEMENT ET LE ASSEMBLÉE LÉGISLATIVE DE LE QUÉBEC DOIVENT JOUER POUR EN PROTÉGER LE CARACTÈRE UNIQUE À LE SEIN DE LE CANADA . 
ELLE RECONNAÎT ÉGALEMENT LES ASPIRATIONS LÉGITIMES DE TOUTES LES PROVINCES ET LEUR ÉGALITÉ DE STATUT À LE SEIN DE LA CONFÉDÉRATION , ET AUSSI QUE IL EST ÉQUITABLE DE FAIRE EN SORTE QUE TOUS LES POUVOIRS QUE UNE FUTURE MODIFICATION CONSTITUTIONNELLE POURRAIT ATTRIBUER À UNE PROVINCE SOIENT ACCESSIBLES À TOUTES LES AUTRES . 
JE CROIS QUE LE CANADA A LE BONHEUR DE COMPTER DE NOMBREUSES RÉGIONS QUI ONT ELLES AUSSI UN CARACTÈRE UNIQUE . 
BREF , LA DÉCLARATION DE CALGARY RECONNAÎT LA RÉALITÉ . 
VOILÀ POURQUOI IL EST SI REGRETTABLE QUE LE BLOC QUÉBÉCOIS ET LE GOUVERNEMENT PROVINCIAL DE LE QUÉBEC NE AIENT PAS CONSULTÉ LES QUÉBÉCOIS SUR CET IMPORTANT SUJET DE DIALOGUE . 
LA DÉCLARATION DE CALGARY INSISTE SUR LE ÉGALITÉ DE LES GENS , LE ÉGALITÉ DE LES PROVINCES ET LE ÉGALITÉ DE LES POUVOIRS . 
SI UNE PROVINCE SE VOYAIT CONFÉRER DE LES POUVOIRS , ILS DEVRAIENT ÊTRE ACCESSIBLES À TOUTES LES AUTRES . 
NOUS DEMANDONS CEPENDANT À TOUS LES DÉPUTÉS DE RECONNAÎTRE LEURS RESPONSABILITÉS DE PARLEMENTAIRES ET DE SE DÉCLARER EN FAVEUR DE UN CANADA FORT ET UNI . 
EN TERMINANT , JE TIENS À RÉITÉRER MON APPUI À CETTE MOTION EN TANT QUE DÉPUTÉ , EN TANT QUE ALBERTAIN ET EN TANT QUE CANADIEN . 
JE ESPÈRE SINCÈREMENT QUE LES DÉPUTÉS DE LE PARTI MINISTÉRIEL COMPRENDRONT QUE IL EST SAGE DE METTRE LEUR ÉNERGIE ET LEUR ENTHOUSIASME À CONTRIBUTION POUR ASSURER LE SUCCÈS DE LE INITIATIVE DE CALGARY QUI FAIT TELLEMENT POUR FAVORISER LE DIALOGUE ENTRE TOUT LE MONDE , ET DE VOTER EN FAVEUR DE LA MOTION . 
JE ESPÈRE AUSSI QUE LES DÉPUTÉS DE LE BLOC QUÉBÉCOIS AGIRONT DANS LE INTÉRÊT SUPÉRIEUR DE TOUS LES QUÉBÉCOIS ET EXHORTERONT LEURS MAÎTRES À QUÉBEC DE LAISSER LEURS ÉLECTEURS EXPRIMER LEUR OPINION À CE SUJET . 
TOUS LES CANADIENS DOIVENT AVOIR LA POSSIBILITÉ DE SE EXPRIMER SUR LE UNITÉ DE NOTRE BEAU GRAND PAYS . 
JE PROPOSE : 
QUE ON MODIFIE LA MOTION EN AJOUTANT IMMÉDIATEMENT APRÈS LES MOTS « LE ÉGALITÉ DE LES CITOYENS ET DE LES PROVINCES » , DE CE QUI SUIT : 
« SANS STATUT SPÉCIAL POUR QUICONQUE » . 
LE VICE - PRÉSIDENT : 
LA PRÉSIDENCE PRENDRA LA PROPOSITION DE AMENDEMENT EN DÉLIBÉRÉ POUR LE MOMENT . 
M . MARK MUISE ( WEST NOVA , PC ) : 
MONSIEUR LE PRÉSIDENT , À LE COURS DE LA DERNIÈRE CAMPAGNE ÉLECTORALE , LES RÉFORMISTES ONT DIT QUE LES PERSONNES DE LE QUÉBEC NE ÉTAIENT PAS DIGNES DE GÉRER CE PAYS . 
QUAND JE ENTENDS CELA ET QUE JE LIS DE LES MOTIONS TELLES QUE CELLE - CI QUI DIT QUE LES RÉFORMISTES VIRENT DE 180 DEGRÉS , JE NE SUIS PAS CAPABLE DE ACCEPTER CELA NI ACCEPTER LE FAIT QUE ILS AGISSENT CONTRE LE UNITÉ NATIONALE . 
ILS SEMBLENT APPORTER DE LES ARGUMENTS QUI NE SONT VALIDES QUE POUR UNE JOURNÉE BIEN DÉFINIE , SOIT CELLE - CI . 
ILS NE PARLENT PAS POUR LE BIEN DE TOUT LE CANADA . 
M . PETER GOLDRING : 
MONSIEUR LE PRÉSIDENT , JE NE SAIS TROP À QUOI LE DÉPUTÉ FAIT ALLUSION . 
JE NE PEUX QUE PARLER DE MON CAS . 
JE SIÈGE ICI , À LA CHAMBRE DE LES COMMUNES , EN RAISON DE LE DERNIER RÉFÉRENDUM . 
LE JOUR DE LE RÉFÉRENDUM , JE ÉTAIS EN VISITE À QUÉBEC ET JE AI VU COMMENT LE VOTE SE EST DÉROULÉ . 
CE EST À BORD DE LE AVION QUI ME RAMENAIT À EDMONTON QUE JE ME SUIS DÉCIDÉ À COMMUNIQUER AVEC LES PARTIS POLITIQUES POUR DÉCOUVRIR LEUR POSITION EN CE QUI CONCERNE LE UNITÉ NATIONALE . 
JE AI DISCUTÉ AVEC DE LES REPRÉSENTANTS DE PLUSIEURS PARTIS ET LE PARTI RÉFORMISTE ÉTAIT LE SEUL À POSSÉDER UN PLAN FAVORISANT LE UNITÉ NATIONALE QUE JE POUVAIS APPUYER SANS RÉSERVE . 
M . PIERRE BRIEN ( TÉMISCAMINGUE , BQ ) : 
MONSIEUR LE PRÉSIDENT , JE VAIS ME INSÉRER DANS CETTE CHICANE ENTRE COLLÈGUES CONSERVATEURS ET RÉFORMISTES . 
M . MICHEL BELLEHUMEUR : 
ILS SONT DE LA MÊME FAMILLE . 
M . PIERRE BRIEN : 
ILS SONT DE LA MÊME FAMILLE . 
ON SE EST FAIT REPROCHER CELA TANTÔT , MAIS ON PEUT VOIR QUE IL Y A UNE CHICANE DE FAMILLE PAS MAL PLUS IMPORTANTE DANS CE COIN - LÀ DE LA CHAMBRE . 
JE AIMERAIS QUE IL ME EXPLIQUE EN QUOI ILS PEUVENT NOUS DONNER UNE LEÇON DE ESPRIT DÉMOCRATIQUE , QUAND ON SAIT QUE À LE QUÉBEC , DEPUIS 15 ANS , IL Y A EU TROIS RÉFÉRENDUMS , IL Y A EU DIFFÉRENTES AVENUES DE CONSULTATIONS SUR LE DOSSIER CONSTITUTIONNEL , ON A EU DE LES EXERCICES ÉMINEMMENT DÉMOCRATIQUES QUE SONT LES RÉFÉRENDUMS . 
POURQUOI NE PARTAGE IL PAS LE POINT DE VUE DE SON COLLÈGUE DE LE NPD QUI DIT QUE LA BALLE EST CLAIREMENT DANS LA COUR DE LES FÉDÉRALISTES ET QUE CEUX - CI DEVRAIENT DE ABORD SE ENTENDRE ENTRE EUX SUR CE QUE ILS SONT CAPABLES DE OFFRIR À LES QUÉBÉCOIS ? 
LE ÉTAPE PRÉALABLE À TOUTE CONSULTATION DE LES QUÉBÉCOIS EST DE DÉFINIR ENTRE EUX CE QUE ILS SONT CAPABLES DE OFFRIR . 
POURQUOI NE PARTAGE IL PAS LE AVIS DE SON COLLÈGUE DE LE NPD À CE SUJET ? 
M . PETER GOLDRING : 
MONSIEUR LE PRÉSIDENT , JE CROIS FERMEMENT DANS LA POSITION DE CONSULTATION ADOPTÉE PAR LE PARTI RÉFORMISTE . 
ON FAIT INTERVENIR LA POPULATION . 
EN CONSULTANT LA MASSE , ON ENTENDRA PLUS DE VÉRITÉS ET DE PROPOS INTELLIGENTS QUE JAMAIS AUPARAVANT . 
JE TIENS ÉGALEMENT À RÉPÉTER QUE LE RÉFÉRENDUM TENU IL Y A DEUX ANS ÉTAIT LE RÉSULTAT DE 35 ANNÉES DE MAUVAISE GESTION DE LA PART DE LES PARTIS POLITIQUES QUI SE SONT SUCCÉDÉ À OTTAWA ET QUI NOUS ONT MENÉS À LE BORD DE LE PRÉCIPICE , À LE BORD DE LE ÉCLATEMENT DE LE PAYS . 
CE EST À CAUSE DE LA GESTION DE LES PARTIS FÉDÉRAUX . 
M . DICK HARRIS ( PRINCE GEORGE - BULKLEY VALLEY , RÉF . ) : 
MONSIEUR LE PRÉSIDENT , CE EST AVEC UN GRAND PLAISIR QUE JE PRENDS PART À LE DÉBAT DE AUJOURD' HUI SUR LA RÉSOLUTION . 
NOUS TRAITONS DE CE QUI EST OU DEVRAIT ÊTRE UNE PRIORITÉ POUR LES COMMUNES , LE UNITÉ NATIONALE . 
UNE CHOSE ME APPARAÎT CLAIREMENT : IL Y A UNE ÉNORME DIFFÉRENCE ENTRE LE APPROCHE ET LA DÉFINITION DE LA NOTION DE UNITÉ QUI SONT PROPRES À LE PARTI RÉFORMISTE ET CELLES DE LES CONSERVATEURS , DE LES LIBÉRAUX ET DE LES BLOQUISTES . 
POUR LES DÉPUTÉS DE CES TROIS AUTRES PARTIS , CONSERVATEURS , LIBÉRAUX ET SÉPARATISTES , LE UNITÉ , CE EST UNE AFFAIRE DE POLITIQUE ET DE POUVOIR POLITIQUE . 
CE QUI NOUS DISTINGUE , CE EST QUE , POUR NOUS , UNITÉ VEUT DIRE RASSEMBLER NOTRE PAYS , AVOIR UN PAYS UNI DONT LES HABITANTS ONT LEUR MOT À DIRE SUR LE AVENIR NATIONAL . 
LA POLITIQUE NE A RIEN À Y VOIR . 
CELA NE A RIEN À VOIR AVEC LA POLITIQUE CONSERVATRICE DE BRIAN MULRONEY , QUI A FAIT APPEL À LES SÉPARATISTES UNIQUEMENT POUR PRENDRE LE POUVOIR . 
CELA NE A RIEN À VOIR NON PLUS AVEC LA POLITIQUE DE LES BLOQUISTES , QUI , AVEC LEURS BONIMENTS DE CHARLATANS , ONT RÉUSSI À CONVAINCRE TANT DE QUÉBÉCOIS QUE ILS PARVIENDRAIENT À UNE SORTE DE NIRVANA SI SEULEMENT ILS CRÉAIENT LEUR PROPRE PAYS . 
RIEN À VOIR NON PLUS AVEC LA POLITIQUE DE LE PARTI LIBÉRAL , QUI CHERCHE À RENOUER AVEC SES RACINES À LE QUÉBEC . 
POUR NOUS , IL SE AGIT DE UNITÉ , IL SE AGIT DE UNIR LE PAYS , DE FAIRE LE UNITÉ DE LES SIMPLES CITOYENS AUTOUR DE LA CONVICTION QUE ON PEUT MIEUX RÉUSSIR À RENFORCER LE CANADA EN UNISSANT TOUS SES HABITANTS SOUS UN SEUL DRAPEAU , DANS UNE SEULE NATION , COMME UN SEUL PEUPLE . 
VOILÀ LA DIFFÉRENCE . 
LEURS ARGUMENTS SONT INCROYABLES , CAR NOUS SAVONS QUELS OBJECTIFS SE CACHENT DERRIÈRE . 
PLUS PARTICULIÈREMENT , NOUS APPUYONS LES PRINCIPES ET LA CONVICTION QUI ANIMENT LE PROCESSUS DE CALGARY : LES PERSONNES LES PLUS IMPORTANTES , LE FACTEUR LE PLUS IMPORTANT DANS TOUT CE DÉBAT SUR LE UNITÉ , CE SONT LES SIMPLES CITOYENS QUI AIMENT LEUR PAYS . 
CE EST LE UNE DE LES CHOSES QUE ON ÉCARTE DE LE DÉBAT DEPUIS PLUS DE 30 ANS . 
LES LIBÉRAUX COMME LES CONSERVATEURS ONT LAISSÉ CELA DE CÔTÉ . 
ILS PRÉFÈRENT TRACER LEUR PLAN DIRECTEUR DANS LES ARRIÈRE - BOUTIQUES AVEC LEURS STRATÈGES POLITIQUES . 
VOILÀ CE QUI NE VA PAS ET CE EST CE QUI EXPLIQUE LE ÉCHEC DE LES ACCORDS DE LE LAC MEECH ET DE CHARLOTTETOWN . 
LES VIEUX PARTIS NE CONSULTENT JAMAIS LA POPULATION . 
CE EST CE QUI FAIT LA DIFFÉRENCE ENTRE LE OBJET DE LA DÉCLARATION DE CALGARY ET LES TENTATIVES DE LES CONSERVATEURS DE MULRONEY , PUIS DE LES LIBÉRAUX QUI ONT UNI LEURS VOIX POUR FAIRE VALOIR LES AVANTAGES DE LE ACCORD DE CHARLOTTETOWN POUR LE CANADA . 
VOILÀ LE EXPLICATION DE LEUR LE ÉCHEC . 
LE NPD AVAIT AUSSI DONNÉ SON APPUI . 
ILS ONT ÉCHOUÉ PARCE QUE ILS NE ONT PAS DE ABORD CONSULTÉ LA POPULATION POUR SAVOIR CE QUE ELLE PENSAIT . 
LES CONSERVATEURS , LES LIBÉRAUX ET LES BLOQUISTES JUGENT INSENSÉE LE IDÉE DE LES RÉFORMISTES , SELON LAQUELLE LES CANADIENS DOIVENT PARTICIPER À LE DÉBAT . 
NOUS VOULONS ÉLABORER UN PLAN QUI SOIT CRÉDIBLE ET CELA NE PEUT SE FAIRE QUE EN CONSULTANT LA POPULATION . 
DANS LE PASSÉ , LES PARTIS POLITIQUES QUI ÉTAIENT REPRÉSENTÉS À LA CHAMBRE NE AVAIENT AUCUNE CRÉDIBILITÉ EN CE QUI CONCERNE LE ÉLABORATION DE UN PLAN SUR LE UNITÉ . 
NOUS LE CONSTATONS DEPUIS 30 ANS . 
ILS ONT ÉCHOUÉ . 
ILS PRÉFÈRENT ALIMENTER LA QUERELLE ENTRE LIBÉRAUX ET SÉPARATISTES ET ENTRE CONSERVATEURS ET SÉPARATISTES AFIN DE SE ASSURER LE POUVOIR DANS LA PROVINCE DE QUÉBEC SANS LE MOINDRE SOUCI POUR LE UNITÉ CANADIENNE , NE SONGEANT QUE À LE POUVOIR POLITIQUE QUE ILS POURRAIENT TIRER DE LES POLITIQUES DE APAISEMENT . 
LE ASPECT IMPORTANT DE LA DÉCLARATION DE CALGARY QUE NOUS VOULONS FAIRE RESSORTIR DANS CE DÉBAT , CE EST QUE LE IDÉE NE EST PAS VENUE DE OTTAWA . 
CE SONT LES PREMIERS MINISTRES DE LES PROVINCES ET LES CHEFS DE LES TERRITOIRES QUI LE ONT SOULEVÉE . 
CE EST UN PLAN QUI INVITE LA PARTICIPATION DE TOUS LES CANADIENS ET QUI LES AMÈNE À FAIRE UN CONSENSUS SUR LA MANIÈRE DE RÉALISER LE UNITÉ CANADIENNE . 
IL EST GRAND TEMPS QUE LES CANADIENS MONTRENT À LES POLITICIENS COMMENT LE CANADA DEVRAIT FONCTIONNER , ET NON QUE LES POLITICIENS DISENT À LE CANADIENS COMMENT LE UNITÉ DEVRAIT FONCTIONNER . 
JE INVITE TOUS LES CANADIENS À PRENDRE PART À LE DÉBAT COMME NOUS ALLONS LE FAIRE AUJOURD' HUI , À EXPRIMER LEURS OPINIONS ET À PARTICIPER À LES RÉUNIONS SUR LE UNITÉ QUI AURONT LIEU PARTOUT À LE CANADA . 
CE EST UNE CHOSE QUE LES CONSERVATEURS NE PERMETTAIENT PAS À LE ÉPOQUE DE BRIAN MULRONEY , QUE ILS NE ONT PAS PERMIS À LE MOMENT DE LE ACCORD DE CHARLOTTETOWN ET QUE LES SÉPARATISTES NE ENVISAGERAIENT MÊME JAMAIS . 
ILS PRÉFÉRERAIENT QUE LEURS BEAUX PARLEURS DE CHEFS PERPÉTUENT LE RÊVE DE UN PAYS MAGNIFIQUE QUI PEUT EXISTER ET SURVIVRE SANS LE RESTE DE LE CANADA , QUAND ILS SAVENT QUE CE NE EST PAS VRAI . 
LA DÉCLARATION DE CALGARY NE EST PAS UNE AFFAIRE RÉGLÉE . 
CE NE EST QUE LE DÉBUT DE UN PROCESSUS QUI PEUT MENER À LA SOLUTION DE LA CRISE DE LE UNITÉ CANADIENNE . 
PAR CONSÉQUENT , IL Y A DE LES INTÉRÊTS IMPORTANTS À CONSIDÉRER . 
POURQUOI ? 
PARCE QUE CELA NE FAIT QUE CRÉER DE LES PROBLÈMES . 
CELA CRÉE DE LES PROBLÈMES DEPUIS 30 ANS , COMME NOUS POUVONS LE CONSTATER AUJOURD' HUI À LA CHAMBRE EN ÉCOUTANT LES LIBÉRAUX DE LE QUÉBEC ET LES SÉPARATISTES PLAISANTER À QUI MIEUX MIEUX . 
ON LE VOIT LORSQUE LES CONSERVATEURS SE EN MÊLENT . 
UNE PROVINCE NE PEUT PAS ÊTRE SUPÉRIEURE À LES AUTRES . 
PEU IMPORTE LA PROVINCE DONT ON PARLE , QUE IL SE AGISSE DE MA PROVINCE NATALE , LA COLOMBIE - BRITANNIQUE , DE LE ALBERTA , DE LA SASKATCHEWAN OU DE LE QUÉBEC , IL NE DOIT PAS Y AVOIR DE STATUT SPÉCIAL . 
PERSONNE NE VEUT VIVRE DANS UNE PROVINCE DE SECONDE CATÉGORIE . 
AUCUN CANADIEN NE DEVRAIT BÉNÉFICIER DE DROITS QUE NE ONT PAS LES AUTRES CANADIENS ET LE ABSENCE DE ÉGALITÉ NE FAIT QUE ACCROÎTRE LE RESSENTIMENT RÉGIONAL ET LA DIVISION NATIONALE . 
SANS ÉGALITÉ , LES CANADIENS NE PEUVENT PAS AVOIR UN SENTIMENT COLLECTIF DE UNITÉ NATIONALE . 
ALORS QUE LES CONSERVATEURS , LES LIBÉRAUX ET LES SÉPARATISTES PRÉFÈRENT PARLER DE CE QUI VAUT MIEUX À LE PLAN RÉGIONAL , LE PARTI RÉFORMISTE VEUT PARLER DE ÉGALITÉ ET DEMANDE QUE TOUTES LES RÉGIONS DE LE PAYS , TOUTES LES PROVINCES ET TOUS LES CANADIENS SOIENT TOUS ÉGAUX SOUS LE MAGNIFIQUE DRAPEAU CANADIEN QUI DÉCORE CETTE CHAMBRE . 
LE ÉGALITÉ SIGNIFIE AUSSI LA FIN DE LE FÉDÉRALISME DOMINATEUR . 
NOUS , DE LE PARTI RÉFORMISTE , PARLONS DE LE ATTRIBUTION DE COMPÉTENCES , PARLONS DE NOUS DÉBARRASSER DE CE GOUVERNEMENT CENTRAL FORT QUI DICTE À LES PROVINCES CE QUE ELLES DOIVENT FAIRE DANS DE LES DOMAINES DONT IL NE DEVRAIT MÊME PAS SE MÊLER . 
OUI , NOUS PROPOSONS DE TRANSFÉRER À LE GOUVERNEMENT DE LE QUÉBEC DE LES POUVOIRS QUI DEVRAIENT LUI REVENIR . 
NOUS PROPOSONS EN MÊME TEMPS DE TRANSFÉRER CES MÊMES POUVOIRS À LES AUTRES PROVINCES . 
JE NE PEUX PAS CROIRE QUE LES SÉPARATISTES QUI SIÈGENT ICI NE POURRAIENT PAS ÊTRE DE ACCORD AVEC NOUS LORSQUE NOUS PROPOSONS DE TRANSFÉRER À LEUR PROVINCE DE LES POUVOIRS DANS DE LES DOMAINES DONT LE GOUVERNEMENT FÉDÉRAL NE DEVRAIT PAS SE MÊLER . 
ET POURTANT , ILS NE LE SONT PAS PARCE QUE CELA NE EST PAS CONFORME À LE GRAND MENSONGE QUE ILS RACONTENT À LE PEUPLE QUÉBÉCOIS . 
LES LIBÉRAUX DE EN FACE RIENT QUAND NOUS PARLONS DE UNITÉ . 
CELA NE ENTRE PAS DANS LEUR IDÉOLOGIE . 
ILS SE INTÉRESSENT DAVANTAGE À LA POLITIQUE , COMME JE LE AI DIT PLUS TÔT . 
JE DEMANDE À LES DÉPUTÉS DE APPUYER CETTE RÉSOLUTION ET DE FAIRE EN SORTE QUE NOUS FASSIONS UN AUTRE PAS VERS LE UNITÉ DE NOTRE PAYS . 
M . CLIFFORD LINCOLN ( LAC - SAINT - LOUIS , LIB . ) : 
IL NE FAUT FAIRE CONFIANCE À PERSONNE SAUF À LES RÉFORMISTES QUI , COMME PAR MAGIE , ONT TROUVÉ LA FORMULE IDÉALE EN MATIÈRE DE UNITÉ . 
LE DÉPUTÉ DIT QUE NOUS NE NOUS SOUCIONS GUÈRE DE LE UNITÉ CANADIENNE . 
JE TROUVE SES PAROLES TRÈS OFFENSANTES . 
JE TROUVE EXTRÊMEMENT BLESSANT QUE LES RÉFORMISTES NOUS DISENT QUE PERSONNE DE ENTRE NOUS NE SE SOUCIE DE LE UNITÉ CANADIENNE , COMME SE ILS AVAIENT LE MESSAGE IDÉAL , COMME SE ILS DÉTENAIENT LA VÉRITÉ , COMME SE ILS AVAIENT LES RÉPONSES À TOUTES LES QUESTIONS ET QUE TOUS LES AUTRES AVAIENT TORT . 
LE DÉPUTÉ ACCUSE LES LIBÉRAUX DE NE PAS AVOIR MENÉ DE CONSULTATIONS SUR LE ACCORD DE CHARLOTTETOWN . 
LE DÉPUTÉ DEVRAIT REVOIR SON DOSSIER . 
JE PENSE SINCÈREMENT QUE EN PRÉSENTANT CETTE MOTION QUI COMPORTE BIEN DE LES ASPECTS INTÉRESSANTS , LE PARTI RÉFORMISTE DEVRAIT ESSAYER DE NOUS RALLIER TOUS SE IL A VRAIMENT À COEUR LE UNITÉ , À LE LIEU DE SIMPLEMENT PRÉTENDRE DÉTENIR LE MESSAGE IDÉAL ET DE MAUDIRE TOUS LES AUTRES . 
À MON AVIS , CE EST UN MESSAGE TRÈS TRISTE QUE LE PARTI RÉFORMISTE NOUS LIVRE . 
M . DICK HARRIS : 
MONSIEUR LE PRÉSIDENT , SI LE DÉPUTÉ AVAIT ÉCOUTÉ ATTENTIVEMENT , IL SAURAIT QUE JE AI PARLÉ DE LE ÉCHEC LAMENTABLE DE LES LIBÉRAUX , DE LES CONSERVATEURS ET DE LES NÉO - DÉMOCRATES QUI SE SONT JOINTS À EUX , DE LEUR ÉCHEC LAMENTABLE À UNIFIER NOTRE PAYS DEPUIS 30 ANS AINSI QUE DE LA CONFIANCE DE LES CANADIENS QUE , DE CE FAIT , ILS ONT PERDUE ET QUE ILS DOIVENT ESSAYER DE RECONQUÉRIR . 
LA PREMIÈRE CHOSE À FAIRE , CE EST DE INVITER LES CANADIENS À PARTICIPER À LE PROCESSUS , CE QUE ILS NE ONT JAMAIS FAIT DANS LE PASSÉ . 
JE VOUDRAIS SOULIGNER QUE À LE ÉPOQUE DE LE ACCORD DE CHARLOTTETOWN QUI SE EST SOLDÉ PAR UN ÉCHEC , LES LIBÉRAUX SE SONT JOINTS À LES CONSERVATEURS ET À LES NÉO - DÉMOCRATES POUR ESSAYER DE VENDRE CET ACCORD À LES CANADIENS , CES DERNIERS NE AYANT TOUTEFOIS PAS PARTICIPÉ À LE PROCESSUS QUI A MENÉ À LE ACCORD . 
IL EST VRAI QUE NOUS AVONS ASSISTÉ À UN SPECTACLE MINABLE DE UN OCÉAN À LE AUTRE , SPECTACLE AUQUEL ONT PARTICIPÉ DE LES TÉMOINS TRIÉS SUR LE VOLET POUR Y EXPRIMER LEUR OPINION ; LES CANADIENS ORDINAIRES ONT TOUTEFOIS ÉTÉ TENUS À LE ÉCART , ET CE EST POUR CETTE RAISON QUE ILS ONT REJETÉ LE ACCORD DE CHARLOTTETOWN . 
M . JEAN - PAUL MARCHAND ( QUÉBEC - EST , BQ ) : 
DE AILLEURS , MÊME SE ILS ÉTAIENT DÉPUTÉS DE LE PARTI CONSERVATEUR OU DE LE NPD , CE SERAIT LA MÊME CHOSE , SOIT QUE , DANS LE FOND , ILS SE DISPUTENT MAIS ILS SONT TOUS DE ACCORD SUR UNE CHOSE : AVANCER DE LES PROPOSITIONS COMME CELLE DE CALGARY DANS LAQUELLE IL NE Y A QUE DE LES MOTS SANS CONTENU ET SANS POIDS POLITIQUE , MÉPRISANT LES REVENDICATIONS JUSTIFIÉES ET JUSTIFIABLES DE LE QUÉBEC DEPUIS 30 ANS . 
M . DICK HARRIS : 
JE SUIS UN CANADIEN ET JE ADORE MON PAYS . 
SI QUELQUE UN DOIT SE EXCUSER , CE DOIT ÊTRE CE DÉPUTÉ SÉPARATISTE QUI SIÈGE À LA CHAMBRE ET REFUSE DE RECONNAÎTRE LE DRAPEAU CANADIEN , DE CHANTER LE HYMNE CANADIEN À LA CHAMBRE ET QUI PRÔNE JOUR APRÈS JOUR LE DÉMANTÈLEMENT DE NOTRE PAYS . 
SI QUELQUE UN DOIT PRÉSENTER DE LES EXCUSES , CE DOIT ÊTRE CE DÉPUTÉ SÉPARATISTE . 
LEHON. RONALD J . DUHAMEL ( SECRÉTAIRE DE ÉTAT ( SCIENCES , RECHERCHE ET DÉVELOPPEMENT ) ( DIVERSIFICATION DE LE ÉCONOMIE DE LE OUEST CANADIEN ) , LIB . ) : 
MONSIEUR LE PRÉSIDENT , IL ME FAIT PLAISIR DE PARTICIPER À LE DÉBAT AUJOURD' HUI , MAIS AVANT DE DÉBUTER , JE DÉSIRE VOUS INFORMER DE CECI . 
JE VAIS PARTAGER MON TEMPS DE PAROLE AVEC MON COLLÈGUE DE WATERLOO - WELLINGTON . 
IL EST TRÈS TENTANT DE SOULEVER UN CERTAIN NOMBRE DE QUESTIONS QUE LE DERNIER DÉPUTÉ RÉFORMISTE À INTERVENIR A ABORDÉES . 
JE SUIS EXTRÊMEMENT SURPRIS ET DÉÇU PAR LES OBSERVATIONS FORMULÉES . 
ON A DÉCLARÉ QUE LE QUÉBEC NE POURRAIT SE EN SORTIR SEUL . 
QUELLE MERVEILLEUSE FAÇON DE COMMENCER UN DIALOGUE . 
ON A PARLÉ ÉGALEMENT DE UN « SPECTACLE MINABLE » POUR RIDICULISER LES EFFORTS DE LES CANADIENS ET DE LEURS REPRÉSENTANTS ÉLUS POUR ESSAYER DE COMPRENDRE ET DE TROUVER DE LES SOLUTIONS . 
IL Y A DE AUTRES REMARQUES TROP NOMBREUSES POUR LES MENTIONNER . 
JE SUIS TENTÉ DE PARLER DE QUESTIONS COMME LE AFFIRMATION QUE ON A FAITE À LE COURS DE LA DERNIÈRE CAMPAGNE SELON LAQUELLE AUCUN QUÉBÉCOIS NE DEVRAIT JAMAIS PLUS ÊTRE PREMIER MINISTRE . 
JE SUIS TENTÉ - ET JE COMPTE SUR UNE AIDE DIVINE - DE PARLER DE HYPOCRISIE À LE SUJET DE CE QUE ON A DIT DE UNE PART DE LA MAISON DE LE CHEF DE LE OPPOSITION ET DE CE QUE ON A FAIT DE AUTRE PART , MAIS JE RÉSISTERAI À LA TENTATION . 
JE VEUX PARLER DE CE QUI EST PROPOSÉ AUJOURD' HUI PAR UN DÉPUTÉ DE LE PARTI RÉFORMISTE QUE JE TROUVE RAISONNABLE , JE DIRAIS MÊME TOUT À FAIT RAISONNABLE . 
CE EST PEUT - ÊTRE PARCE QUE IL VIENT DE ARRIVER ET QUE TOUS LES AUTRES AUTOUR DE LUI NE ONT PAS ÉTÉ CAPABLES DE SOCIALISER JUSQUE À PRÉSENT . 
IL ARRIVE AVEC UNE PROPOSITION TOUT À FAIT RAISONNABLE , À MON AVIS , QUI VISE À PROMOUVOIR LA CONSULTATION DE LES CANADIENS UN PEU PARTOUT . 
JE APPLAUDIS CETTE APPROCHE . 
MAIS JE CROIS QUE IL DEVRAIT PARLER À SES COLLÈGUES , CAR UN DE SES COLLÈGUES VIENT DE MENTIONNER QUE RIEN NE A ÉTÉ ACCOMPLI PENDANT LES 30 DERNIÈRES ANNÉES . 
UN DE SES COLLÈGUES PRÉTEND QUE CHAQUE FORMATION POLITIQUE NE A RIEN À CONTRIBUER , SAUF LA SIENNE . 
UN DE SES COLLÈGUES A FAIT DE LES COMMENTAIRES QUI NE SONT PAS DIGNES DE ÊTRE MENTIONNÉS À LA CHAMBRE DE LES COMMUNES . 
NÉANMOINS , LA PROPOSITION DONT NOUS DISCUTONS AUJOURD' HUI ET DONT NOUS ALLONS DÉBATTRE MÉRITE DE ÊTRE APPUYÉE . 
ELLE MÉRITE DE ÊTRE APPUYÉE , PUISQUE ON PARLE DE CONSULTATIONS AVEC LES CANADIENS DE PARTOUT À TRAVERS LE PAYS . 
CE QUI ME INTÉRESSERAIT BEAUCOUP , CE EST DE CONNAÎTRE LA POSITION DE CETTE FORMATION POLITIQUE , AINSI QUE LA POSITION DE CHAQUE FORMATION POLITIQUE CONCERNANT LA DÉCLARATION DE CALGARY . 
EST - CE QUE IL EST TROP TÔT POUR SE PRONONCER ? 
IL NE EST PAS TROP TÔT POUR ALLER DIRE À LES AUTRES CE QUE ILS DEVRAIENT FAIRE . 
CE EST CE DONT JE AIMERAIS QUAND MÊME DISCUTER AUJOURD' HUI . 
DONC , NOS FORMATIONS POLITIQUES SONT QUAND MÊME DIFFÉRENTES , MÊME SI ON SE ENTEND PLUS OU MOINS SUR LA PROPOSITION DONT NOUS SOMMES EN TRAIN DE DISCUTER AUJOURD' HUI . 
IL Y A DE NOMBREUSES DIFFÉRENCES SUR LE IMMIGRATION , LE RÔLE DE LES AUTOCHTONES À LE CANADA , LE BILINGUISME , ET JE EN PASSE . 
JE POURRAIS EN DISCUTER BEAUCOUP PLUS LONGUEMENT , MAIS IL NE FAUDRAIT PAS SE TROMPER , IL Y A DE LES DIFFÉRENCES PROFONDES , EXTRÊMEMENT DIFFÉRENTES QUI VONT DANS DE LES DIRECTIONS QUI NE SE REJOINDRONT JAMAIS . 
LORS DE LA RENCONTRE DE LES PREMIERS MINISTRES PROVINCIAUX DE LE CANADA , ON DEMANDAIT DE LES CONSULTATIONS PUBLIQUES . 
CETTE DÉCLARATION EST UN BON POINT DE DÉPART POUR ESSAYER DE COMPRENDRE DAVANTAGE NOTRE PAYS ET CE QUE CHAQUE RÉGION VEUT ET , BIEN SÛR , CE QUE VEULENT LES QUÉBÉCOIS ET LES QUÉBÉCOISES . 
LA DÉCLARATION DE CALGARY EST APPUYÉE PAR UN BON NOMBRE DE GENS PARTOUT À LE PAYS . 
IL EST VRAI QUE CERTAINS SE Y OPPOSENT TOUT À FAIT ET CELA SE COMPREND . 
MAIS UN BON NOMBRE DE PERSONNES RESPONSABLES ENDOSSENT CETTE DÉCLARATION . 
IL EST IMPORTANT QUE LA POPULATION DE LE CANADA DISCUTE DE CETTE PROPOSITION ET QUE ELLE COMPRENNE DAVANTAGE CHAQUE PROVINCE ET TERRITOIRE ET , BIEN SÛR , LE QUÉBEC , QUI EST SOUVENT MAL COMPRIS . 
LES CONSULTATIONS SONT NÉCESSAIRES , PARCE QUE ELLES VONT PEUT - ÊTRE ALLER AU - DELÀ DE LES CONSULTATIONS , EN CE SENS DE EN APPRENDRE DAVANTAGE SUR CE QUE NOUS SOMMES COMME COLLECTIVITÉS . 
JE PARLE DE TOUTES LES COLLECTIVITÉS QUE ON PEUT TROUVER À LE INTÉRIEUR DE LE PAYS . 
ELLES PEUVENT SUSCITER , JE CROIS , LA FIERTÉ . 
ON POURRAIT ARRIVER À LA RÉALISATION QUE IL FAUT TRAVAILLER DAVANTAGE ENSEMBLE , AFIN DE ÊTRE PLUS FORTS ET DE ÊTRE CAPABLES DE RÉPONDRE DANS UN SENS BEAUCOUP PLUS SENSIBLE À LES DIFFÉRENTS BESOINS QUE NOUS AVONS COMME CITOYENS QUE NOUS SOMMES , DE UNE PROVINCE OU DE UNE AUTRE , QUE ON APPARTIENT À UN GROUPE LINGUISTIQUE , À UN GROUPE RELIGIEUX , À UNE CULTURE OU À UNE AUTRE . 
JE VEUX MAINTENANT PARLER DE CERTAINS PRINCIPES . 
JE VAIS COMMENCER AVEC LE ÉGALITÉ . 
JE VEUX PARTAGER AVEC VOUS CE QUE UN CITOYEN CANADIEN A PARTAGÉ AVEC MOI . 
JE LE CITE : « IL SE AGIT LÀ DE UN PRINCIPE AVEC LEQUEL NOUS NE SAURIONS ÊTRE EN DÉSACCORD , UN PRINCIPE DE AILLEURS RECONNU À LE ARTICLE 15 DE LA LOI CONSTITUTIONNELLE DE 1982 . 
IL Y EST FAIT CLAIREMENT MENTION QUE TOUS LES CANADIENS SONT ÉGAUX , SANS CONSIDÉRATION DE SEXE , DE RACE , DE RELIGION , DE CONDITION SOCIALE OU DE FORTUNE . 
ÉNONCER UN TEL PRINCIPE SUFFIT À LUI SEUL À EN DÉMONTRER LE ÉVIDENCE . » 
IL Y A CERTAINES FORMATIONS POLITIQUES , COMME JE LE AI DIT TOUT À LE HEURE , ET JE VAIS ESSAYER DE ME RESTREINDRE , QUI VONT UTILISER QUELQUE CHOSE COMME CECI , LE ÉGALITÉ , POUR PRÉTENDRE QUE CE EST AUTRE QUE . 
MAIS NON , CE EST DANS LA LOI CANADIENNE , CE EST LÀ DEPUIS LONGTEMPS . 
MAINTENANT , EST - CE QUE CE EST TOUJOURS MIS EN APPLICATION DE FAÇON JUSTE ? 
BIEN SÛR JE AI LE IMPRESSION QUE ON POURRAIT TROUVER DE LES EXEMPLES OÙ ÇA NE A PAS ÉTÉ LE CAS , MAIS EN GÉNÉRAL , REGARDONS . 
PENCHONS - NOUS SUR LE ÉGALITÉ DE LES PROVINCES . 
IL NE Y A QUE UN SEUL STATUT JURIDIQUE POUR LES PROVINCES . 
IL NE Y EN A PAS SIX . 
UNE PROVINCE EST UNE PROVINCE . 
AUCUNE NE EST SUPÉRIEURE À LES AUTRES . 
NOUS LE SAVONS . 
MÊME SI ELLES SONT ÉGALES , ELLES SONT QUAND MÊME DIFFÉRENTES AVEC LEURS PROPRES CARACTÉRISTIQUES SOCIO - ÉCONOMIQUES , CULTURELLES ET HISTORIQUES . 
MÊME SI ELLES SONT ÉGALES , ELLES SE DIFFÉRENCIENT LES UNES DE LES AUTRES . 
CE EST CE QUE CERTAINES PERSONNES COMPRENNENT MAL . 
CE FAISANT , ELLES DÉCHIRENT LE PAYS . 
ELLES SONT COUPABLES DE DIVISER NOTRE PAYS . 
LE CANADA , QUI , SELON CERTAINS , STAGNE DEPUIS 30 , 40 OU 50 ANS , FAIT LE ENVIE DE LE MONDE ENTIER . 
PRATIQUEMENT TOUT LE MONDE CONSIDÈRE QUE CE EST LE MEILLEUR PAYS OÙ VIVRE . 
DE LES MILLIONS DE GENS SE SONT EMPRESSÉS DE VENIR SE Y ÉTABLIR . 
PARLONS DE AUTRES PRINCIPES . 
PARLONS DE LA DIVERSITÉ , PARLONS DE LA TOLÉRANCE , DE LA COMPASSION , DE LE ÉGALITÉ DE LES CHANCES . 
DE LES VOIX : 
OH ! OH ! 
LEHON. RONALD J . DUHAMEL : 
CE EST CE QUI NE EST PAS COMPRIS PAR UN NOMBRE DE FORMATIONS POLITIQUES , INCLUANT DE LES DÉPUTÉS QUE JE ENTENDS CRIER . 
COMME LE MENTIONNE LA DÉCLARATION , JE VAIS RÉPÉTER : « LE RESPECT POUR LA DIVERSITÉ ET LE ÉGALITÉ CONSTITUE UN FONDEMENT DE LE UNITÉ , MAIS LE ÉGALITÉ NE EST PAS UN SYNONYME DE UNIFORMITÉ . 
POUR CONCILIER LE PRINCIPE DE ÉGALITÉ AVEC CETTE GRANDE VALEUR QUE EST LA DIVERSITÉ , LE CANADA PEUT COMPTER SUR UN SYSTÈME POLITIQUE QUI , PAR SA SOUPLESSE ET SA FLEXIBILITÉ , FAVORISE LE ENRICHISSEMENT DE NOTRE PATRIMOINE COLLECTIF . 
AUCUN AUTRE EXEMPLE NE ILLUSTRE MIEUX CETTE RÉALITÉ QUE LA QUESTION RELATIVE À LA RECONNAISSANCE DE LE QUÉBEC DANS SON CARACTÈRE UNIQUE » . 
MAIS QUEL EST CE CARACTÈRE UNIQUE ? 
UNE VOIX : 
CE NE SONT QUE DE LES MOTS . 
LEHON. RONALD J . DUHAMEL : 
JE AI ENTENDU QUELQUE UN DIRE QUE CE NE SONT QUE DE LES MOTS . 
CE EST DOMMAGE QUE IL NE PUISSE PAS LE LIRE ET LE COMPRENDRE . 
M . JEAN - PAUL MARCHAND : 
EXPLIQUEZ - NOUS ÇA . 
UNE VOIX : 
LEHON. RONALD J . DUHAMEL : 
OUI , OUI , UNE SEULE PERSONNE . 
ON VA PRENDRE UNE SEULE PERSONNE , DE UNE SEULE PROVINCE ET ON VA PRÉTENDRE QUE IL CONNAÎT LA VÉRITÉ . 
M . MICHEL BELLEHUMEUR : 
LE PREMIER MINISTRE DE LE ONTARIO . 
LEHON. RONALD J . DUHAMEL : 
OH , QUEL EFFORT VOUS FAITES DE COMPRENDRE . 
M . YVES ROCHELEAU : 
DE LES DÉTAILS . 
LEHON. RONALD J . DUHAMEL : 
QUEL BEL EFFORT DE DÉMONTRER À QUEL POINT VOUS ÊTES OUVERT DE ESPRIT , CHER COLLÈGUE . 
M . MICHEL BELLEHUMEUR : 
LE PREMIER MINISTRE DE TORONTO LE A COMPRIS , LUI . 
LEHON. RONALD J . DUHAMEL : 
MAIS CONTINUONS . 
« DANS CE RÉGIME FÉDÉRAL - ET JE TERMINE AVEC CE DERNIER POINT - OÙ LE RESPECT POUR LA DIVERSITÉ ET LE ÉGALITÉ EST UN FONDEMENT DE LE UNITÉ , LE CARACTÈRE UNIQUE DE LA SOCIÉTÉ QUÉBÉCOISE CONSTITUÉ NOTAMMENT DE SA MAJORITÉ FRANCOPHONE , DE SA CULTURE ET DE SA TRADITION DE DROIT CIVIL EST FONDAMENTAL POUR LE BIEN - ÊTRE DE LE CANADA . » 
JE POURRAIS CONTINUER , MALHEUREUSEMENT ON ME COUPE LA PAROLE . 
AH , QUE CE EST ANTIDÉMOCRATIQUE , VOUS NE CROYEZ PAS ? 
LE VICE - PRÉSIDENT : 
À LE ORDRE , SE IL VOUS PLAÎT . 
AVANT DE PASSER À LA PÉRIODE DE QUESTIONS ET COMMENTAIRES , JE DOIS DIRE QUE JE AI EXAMINÉ LE AMENDEMENT PROPOSÉ PAR LE HONORABLE DÉPUTÉ DE EDMONTON - EST ET QUE JE DÉCLARE CET AMENDEMENT RECEVABLE . 
LE DÉBAT PORTE DONC MAINTENANT SUR LE AMENDEMENT . 
LA PAROLE EST À LE HONORABLE DÉPUTÉ DE CHICOUTIMI POUR UN COMMENTAIRE OU UNE QUESTION . 
M . ANDRÉ HARVEY ( CHICOUTIMI , PC ) : 
MONSIEUR LE PRÉSIDENT , JE SERAI BREF . 
À MON AVIS , CE DÉBAT ILLUSTRE TRÈS BIEN QUE LE DOSSIER CONSTITUTIONNEL , EN TANT QUE POLITICIENS , EST UN PEU NOTRE VOCATION À TOUS . 
NOUS NE AVONS PAS TOUJOURS EU UN APPORT TRÈS POSITIF . 
À LE CONTRAIRE , LES ÉCHECS DE LE PASSÉ ONT RAREMENT ÉTÉ ATTRIBUABLES À LES CONCITOYENS QUE NOUS REPRÉSENTONS , MAIS TRÈS SOUVENT À DE LES POLITICIENS QUI ONT FAIT PREUVE DE UNE IRRESPONSABILITÉ DONT NOUS SUPPORTONS ENCORE AUJOURD' HUI LE LOT . 
JE SUIS TRÈS SURPRIS . 
JE ESPÈRE QUE LE PARTI LIBÉRAL DE LE CANADA EST EN CAUCUS , PARCE QUE SA POSITION EST ASSEZ DIFFICILE À CONCEVOIR : ACCEPTER ET APPUYER UNE RÉSOLUTION DE LA PART DE UN PARTI DONT LE PASSÉ NE EST PAS DE LES PLUS GLORIEUX , ACCEPTER UNE PROPOSITION QUI DEMANDE DE ALLER INFORMER LES QUÉBÉCOIS , CONSULTER LES QUÉBÉCOIS SUR UNE OEUVRE COMPLÈTEMENT INACHEVÉE . 
IL FAUT TOUJOURS ESSAYER DE DONNER UNE CHANCE À LES GENS DE MODIFIER LEUR POINT DE VUE . 
MAIS QUAND ON LIT LES TEXTES DEM. MANNING , QUI A DÉJÀ DIT , EN PASSANT , LORS DE LE ÉCHEC DE LE ACCORD DE LE LAC MEECH : « JE AIMERAIS VOIR UN DE LES PREMIERS MINISTRES DE LE OUEST LIVRER LE COUP DE GRÂCE À LE ACCORD » , IL EST DIFFICILE DE CONCEVOIR QUE IL PUISSE CHANGER AUSSI RAPIDEMENT SON FUSIL DE ÉPAULE . 
QUAND ON REGARDE PLUS RÉCEMMENT TOUTE LA PUBLICITÉ QUI A ÉTÉ FAITE CONTRE LES POLITICIENS DE LE QUÉBEC , CE EST BEAUCOUP DEMANDER DE APPUYER UNE RÉSOLUTION COMME CELLE DE AUJOURD' HUI QUI VISE À CONSULTER LES QUÉBÉCOIS . 
LE PARTI LIBÉRAL APPUIE UNE MOTION QUI EST DE LA PROVOCATION PURE ET SIMPLE ENVERS TOUS LES CITOYENS DE LE QUÉBEC ET ENVERS TOUS LES CANADIENS FRANÇAIS . 
JE DEMANDE À MON COLLÈGUE DE LE PARTI LIBÉRAL SE IL APPUIERAIT LE RETRAIT DE LA MOTION DE LE PARTI RÉFORMISTE PAR RESPECT POUR TOUS LES QUÉBÉCOIS ET TOUS LES CANADIENS FRANÇAIS DANS LE ESPOIR DE EN ARRIVER UN JOUR AVEC UN PROJET QUI SERAIT SUBSTANTIEL , QUI RESPECTERAIT LES DEMANDES HISTORIQUES DE LE QUÉBEC ET QUI SERAIT EN MESURE DE RECEVOIR LE APPUI DE TOUT LE MONDE . 
JE DEMANDE TRÈS CORDIALEMENT À MON COLLÈGUE CE QUE IL EN PENSE , PARCE QUE LA DÉMARCHE QUE ON POURSUIT AUJOURD' HUI EST UNE DÉMARCHE DE AFFRONTEMENT QUI , LOIN DE AMÉLIORER LE DÉBAT , CONTRIBUE À LE DÉTÉRIORER DE UNE FAÇON QUI NE EST PAS POSITIVE . 
ENCORE UNE FOIS , CE EST FAIRE PREUVE DE IRRESPONSABILITÉ EN TANT QUE POLITICIENS QUE DE VOULOIR ACCÉLÉRER UNE DÉMARCHE SANS DOSSIER ENTRE LES MAINS . 
LEHON. RONALD J . DUHAMEL : 
MONSIEUR LE PRÉSIDENT , TOUT DE ABORD , JE CROIS QUE CE EST CONNU , MÊME PAR MES COLLÈGUES DE LE QUÉBEC , JE AI UN ÉNORME RESPECT POUR LE QUÉBEC ; JE EN AI TOUJOURS EU . 
CE NE EST DONC PAS UNE QUESTION DE RESPECT ; CE RESPECT EXISTE CHEZ MOI ET CHEZ MES COLLÈGUES . 
QUE SE PASSE IL AUJOURD' HUI ? 
OUI , IL EST VRAI QUE LE PARTI QUI A PROPOSÉ CETTE MOTION NE A PAS UN PASSÉ GLORIEUX SUR CETTE QUESTION . 
MAIS IL EST VRAI QUE IL Y EN A DE CETTE FORMATION QUI FONT UN EFFORT . 
UN EFFORT À QUEL SUJET ? 
POURQUOI NE PAS DONNER LA CHANCE À CE NOUVEL ARRIVÉ QUI POURRAIT PEUT - ÊTRE ÉCLAIRER CERTAINS DE SES COLLÈGUES QUI SONT MOINS ÉCLAIRÉS , SI VOUS AVEZ ÉCOUTÉ LES DISCOURS AUJOURD' HUI . 
NOUS PARLONS DE CONSULTATIONS . 
LA NÔTRE EST TRÈS CLAIRE : NOUS APPUYONS LA CONSULTATION ET NOUS APPUYONS LE CARACTÈRE UNIQUE DE LE QUÉBEC . 
DE AILLEURS , CE EST CETTE FORMATION POLITIQUE QUI A APPORTÉ UNE PROPOSITION SUR LAQUELLE ON A VOTÉ ET QUI APPUYAIT LE CARACTÈRE DISTINCT DE LE QUÉBEC . 
EST - CE QUE LES GENS ONT OUBLIÉ CELA ? 
CE EST CETTE FORMATION POLITIQUE - CI QUI LE A FAIT . 
M . LYNN MYERS ( WATERLOO - WELLINGTON , LIB . ) : 
MONSIEUR LE PRÉSIDENT , JE SUIS HEUREUSE DE PRENDRE LA PAROLE À LA CHAMBRE POUR DONNER MON POINT DE VUE SUR LA TRÈS IMPORTANTE MOTION PRÉSENTÉE PAR MON COLLÈGUE DE EDMONTON - STRATHCONA . 
IL NE Y A PAS DE SUJET PLUS IMPORTANT QUE CELUI DE LE UNITÉ DE LE CANADA . 
CE EST UN POINT DE VUE QUE NOUS AVONS CONFIRMÉ DANS LE DISCOURS DE LE TRÔNE , PLUS TÔT CET AUTOMNE , EN INDIQUANT QUE CE ÉTAIT NOTRE PREMIÈRE PRIORITÉ . 
COMME NOUS LE SAVONS TOUS , LES PREMIERS MINISTRES DE NEUF PROVINCES , AINSI QUE LES LEADERS DE LES DEUX TERRITOIRES , SE SONT RENCONTRÉS LE 14 SEPTEMBRE POUR DISCUTER DE UN CADRE DE CONSULTATION DE LA POPULATION EN VUE DE RENFORCER LA FÉDÉRATION CANADIENNE . 
LE RÉSULTAT , CE EST LA DÉCLARATION DE CALGARY . 
LES PRINCIPES ET LES CONSULTATIONS DE CALGARY SONT UN GESTE DE BONNE VOLONTÉ À LE ÉGARD DE TOUS LES CANADIENS , CE QUI COMPREND AUSSI BIEN LES QUÉBÉCOIS QUE LES AUTOCHTONES OU LES MINORITÉS LINGUISTIQUES . 
MÊME SI LA DÉCLARATION NE EST PAS UN DOCUMENT LÉGAL , NI UNE PROPOSITION DE MODIFICATION CONSTITUTIONNELLE , NOUS PENSONS QUE CE EST UN PAS IMPORTANT DANS LA BONNE DIRECTION . 
CE EST UNE INVITATION DE 11 CHEFS DE GOUVERNEMENT À TOUS LES CANADIENS DE TOUTES LES RÉGIONS À RÉFLÉCHIR À LES VALEURS QUE NOUS PARTAGEONS ET À SE LANCER DANS DE NOUVELLES DISCUSSIONS . 
NOUS ESPÉRONS AUSSI QUE LES PRINCIPES DE CALGARY NOUS CONDUIRONT À UN CONSENSUS SUR LES VALEURS FONDAMENTALES DE NOTRE PAYS , PARMI LESQUELLES FIGURE LE RESPECT DE LE CARACTÈRE UNIQUE DE LE QUÉBEC . 
DE LE CÔTÉ DE LE GOUVERNEMENT , NOUS ENDOSSONS LES PRINCIPES ARRÊTÉS PAR LES PREMIERS MINISTRES , LES LEADERS TERRITORIAUX ET TOUS LES CANADIENS EN VUE DE PROMOUVOIR LE UNITÉ NATIONALE . 
DE PLUS , NOUS APPUYONS LE PROCESSUS DE CONSULTATION LANCÉ PAR CES PREMIERS MINISTRES . 
LES PRINCIPES DE CALGARY SONT LE OEUVRE DE LES PREMIERS MINISTRES DE LES PROVINCES ET DE LES LEADERS DE LES TERRITOIRES . 
LE GOUVERNEMENT FÉDÉRAL NE A PAS PARTICIPÉ À LA RÉUNION DE CALGARY ET COLLABORE FORT PEU À LES CONSULTATIONS QUE MÈNENT ACTUELLEMENT LES PROVINCES ET LES TERRITOIRES . 
CELA ÉTANT DIT , JE AI LE INTENTION DE FAIRE TOUT EN MON POUVOIR POUR PROMOUVOIR LA TENUE DE UN DÉBAT PUBLIC POSITIF SUR LA QUESTION TRÈS IMPORTANTE DE LES PRINCIPES DE LA DÉCLARATION DE CALGARY , TANT DANS MA PROVINCE QUE DANS LE ENSEMBLE DE LE PAYS . 
NOUS SAVONS QUE LE INITIATIVE DE CALGARY A ÉTÉ PRISE NOTAMMENT PARCE QUE LES NEUF PREMIERS MINISTRES ET LES DEUX CHEFS DE LES TERRITOIRES VOULAIENT CONSULTER LEUR POPULATION AFIN DE CRÉER UN MEILLEUR CLIMAT DE TRAVAIL . 
BIEN QUE ELLES EN SOIENT À DE LES STADES DIFFÉRENTS , LES CONSULTATIONS SUR LES PRINCIPES DE LA DÉCLARATION DE CALGARY VONT BON TRAIN DANS LES NEUF PROVINCES ET LES DEUX TERRITOIRES . 
NOUS , LES DÉPUTÉS DE CE CÔTÉ - CI DE LA CHAMBRE , EXHORTONS LES CANADIENS À PARTICIPER À CE PROCESSUS DE CONSULTATION FORT IMPORTANT . 
NOUS LES INVITONS À DONNER LEUR AVIS ET À PROPOSER DE LES AMÉLIORATIONS À APPORTER À LES PRINCIPES QUI ONT ÉTÉ ÉNONCÉS . 
POURQUOI LE GOUVERNEMENT SÉPARATISTE DE LE QUÉBEC REFUSE IL DE CONSULTER LES QUÉBÉCOIS SUR CES PRINCIPES ? 
PERMETTEZ - MOI DE EXAMINER DE PLUS PRÈS CHACUN DE LES SEPT PRINCIPES ÉNONCÉS PAR LES PREMIERS MINISTRES ET LES LEADERS TERRITORIAUX DANS LA DÉCLARATION DE CALGARY . 
PREMIÈREMENT , LE ÉGALITÉ DE LES CITOYENS . 
TOUS LES CANADIENS SONT ÉGAUX ET LEURS DROITS SONT PROTÉGÉS PAR LA LOI . 
CE PRINCIPE EST CONSACRÉ À LE ARTICLE 15 DE LA CHARTE CANADIENNE DE LES DROITS ET LIBERTÉS . 
CELA SIGNIFIE QUE TOUS LES CANADIENS , PEU IMPORTE LEUR SEXE , LEUR RACE , LEUR RELIGION , LEUR CONDITION SOCIALE OU LEUR SITUATION FINANCIÈRE , SONT ÉGAUX DEVANT LA LOI . 
MAIS LE ÉGALITÉ NE VEUT PAS DIRE LE UNIFORMITÉ . 
DANS UNE DÉMOCRATIE COMME LA NÔTRE , LE ÉGALITÉ ET LA LIBERTÉ VONT DE PAIR . 
RIEN NE NOUS OBLIGE À AVOIR LES MÊMES CROYANCES ET PRÉFÉRENCES QUE LES AUTRES . 
NOUS AVONS TOUS LE DROIT DE ÊTRE DIFFÉRENTS . 
AUTREMENT DIT , TOUS LES ENFANTS DE LA FAMILLE SONT ÉGAUX , MAIS CELA NE SIGNIFIE PAS QUE ILS SONT TOUS PAREILS . 
VOILÀ POURQUOI LA CONSTITUTION ELLE - MÊME , PLUS PRÉCISÉMENT LE ARTICLE 36 DE LA LOI CONSTITUTIONNELLE DE 1982 , ENGAGE TOUS LES ORDRES DE GOUVERNEMENT À PROMOUVOIR LE ÉGALITÉ DE LES CHANCES DE TOUS LES CANADIENS DANS LA RECHERCHE DE LEUR BIEN - ÊTRE . 
VOILÀ POURQUOI DIVERSES DISPOSITIONS DE LA CONSTITUTION RECONNAISSENT LES DROITS ANCESTRAUX ET ISSUS DE TRAITÉS DE LES PEUPLES AUTOCHTONES AINSI QUE LES DROITS DONT JOUISSENT NOS MINORITÉS LINGUISTIQUES . 
DEUXIÈMEMENT , LE ÉGALITÉ DE LES PROVINCES . 
NOUS CROYONS QUE LE PRINCIPE DE ÉGALITÉ QUI SE APPLIQUE À LES PERSONNES SE APPLIQUE ÉGALEMENT À LES PROVINCES . 
NOUS ESTIMONS QUE LES PROVINCES ONT UN RANG ÉGAL . 
AUCUNE DE ELLES NE EST SUPÉRIEURE À LES AUTRES ET TOUTES ENTRETIENNENT LE MÊME LIEN JURIDIQUE FONDAMENTAL AVEC LEUR POPULATION RESPECTIVE . 
CELA ÉTANT DIT , JE ME DOIS DE PRÉCISER QUE LEUR ÉGALITÉ DE RANG NE SIGNIFIE PAS QUE ELLES NE PEUVENT PAS ÊTRE DIFFÉRENTES ENTRE ELLES . 
COMME DANS LE CAS DE LES SIMPLES CANADIENS , POUR LES PROVINCES , ÉGALITÉ NE EST PAS SYNONYME DE UNIFORMITÉ . 
TOUTES LES PROVINCES DOIVENT ÊTRE TRAITÉES ÉGALEMENT , MAIS CHACUNE DE ELLES A DE LES BESOINS PARTICULIERS QUI VARIENT SELON LES CIRCONSTANCES . 
CE EST POURQUOI NOTRE SYSTÈME FÉDÉRAL ACCEPTE LES DIFFÉRENCES ET ÉVITE DE METTRE LES PROVINCES DANS UNE STRUCTURE RIGIDE QUI LES EMPÊCHERAIT DE RÉPONDRE À LEURS BESOINS PARTICULIERS . 
TROISIÈMEMENT , LA DIVERSITÉ , LA TOLÉRANCE , LA COMPASSION ET LE ÉGALITÉ DE LES CHANCES . 
LE HISTOIRE DE LE CANADA EST MARQUÉE À LE COIN DE UNE VÉRITABLE OUVERTURE À LES DIFFÉRENCES ET DE UN GÉNÉREUX ESPRIT DE TOLÉRANCE . 
TOUT PAYS A CERTES SES POINTS FAIBLES , MAIS LES CIRCONSTANCES ONT FAIT QUE LE CANADA EST UN PAYS QUI RESPECTE ÉNORMÉMENT TOUS SES CITOYENS , DE OÙ QUE ILS VIENNENT . 
NOTRE ESPRIT ENCLIN À LA CONCERTATION ET À LA COMPASSION A INCITÉ NOS GOUVERNEMENTS FÉDÉRAL ET PROVINCIAUX À CRÉER DE LES PROGRAMMES SOCIAUX QUE LE MONDE ENTIER NOUS ENVIE ET QUI TÉMOIGNENT DE NOTRE DÉSIR DE TRAVAILLER ENSEMBLE POUR QUE TOUS ET CHACUN AIENT DE LES CHANCES ÉGALES ET DE LA COMPASSION QUE NOUS ÉPROUVONS ENVERS LES PLUS DÉMUNIS DE NOTRE SOCIÉTÉ . 
CELA EST TRÈS IMPORTANT . 
QUATRIÈMEMENT , NOTRE IDENTITÉ NATIONALE EST ENRICHIE PAR LES APPORTS DE LES PEUPLES AUTOCHTONES , LA VITALITÉ DE LES LANGUES ANGLAISE ET FRANÇAISE ET LE CARACTÈRE MULTICULTUREL DE LE CANADA . 
À LE INSTAR DE LA DÉCLARATION DE CALGARY ET DE LES RÉCENTES DÉCLARATIONS FAITES PAR LES PREMIERS MINISTRES ET LES CHEFS , LE DISCOURS DE LE TRÔNE RECONNAÎT LA PRÉCIEUSE CONTRIBUTION DE LES PEUPLES AUTOCHTONES À LA CRÉATION DE LE CANADA ET À LA RICHESSE DE NOTRE IDENTITÉ . 
NOUS TRAVAILLONS EN COLLABORATION AVEC LES PEUPLES AUTOCHTONES À LA RÉSOLUTION DE LES PROBLÈMES AUXQUELS ILS SONT CONFRONTÉS . 
LES DEUX LANGUES OFFICIELLES DE LE CANADA CONSTITUENT UNE AUTRE RICHESSE DE NOTRE PAYS . 
LA DUALITÉ LINGUISTIQUE ET LA VIABILITÉ DE DEUX COMMUNAUTÉS LINGUISTIQUES OFFICIELLES PARTOUT À LE PAYS FONT PARTIE INTÉGRANTE DE NOTRE IDENTITÉ NATIONALE . 
UN DE LES ATOUTS DE LE CANADA , CE EST QUE SES DEUX LANGUES OFFICIELLES SONT PARMI CELLES QUI SONT LE PLUS EN USAGE DANS LE MONDE . 
ELLES CONTRIBUENT CONSIDÉRABLEMENT À LE SUCCÈS DE LE CANADA SUR LES PLAN ÉCONOMIQUE , SOCIAL , CULTUREL ET INTERNATIONAL . 
LE CARACTÈRE MULTICULTUREL DE LE CANADA EST UNE SOURCE DE FIERTÉ ET DE ENRICHISSEMENT POUR NOUS TOUS , AINSI QUE UN IDÉAL UNIVERSEL . 
CINQUIÈMEMENT , LE CARACTÈRE UNIQUE DE LA SOCIÉTÉ QUÉBÉCOISE . 
NOTRE RECONNAISSANCE DE LES DIFFÉRENCES LINGUISTIQUES ET CULTURELLES DE LE QUÉBEC RÉPOND À LES BESOINS ET À LE CARACTÈRE UNIQUES DE CE DERNIER , TOUT EN ÉTANT CONFORME À LE PRINCIPE DE LE ÉGALITÉ DE LES PROVINCES ET DE TOUS LES CANADIENS INDIVIDUELLEMENT . 
CE EST POURQUOI LE PARLEMENT A ADOPTÉ UNE RÉSOLUTION RECONNAISSANT CES DIFFÉRENCES . 
CETTE RECONNAISSANCE DE LE QUÉBEC CONSTITUE UN MESSAGE POSITIF À LES QUÉBÉCOIS QUI SOUHAITENT FAIRE PARTIE DE LA GRANDE FAMILLE CANADIENNE . 
ELLE MONTRE À LES QUÉBÉCOIS QUE LE RESTE DE LE CANADA LES ACCEPTE ET RESPECTE LEUR DROIT À LA DIFFÉRENCE . 
ELLE EST AUSSI LIÉE À DE AUTRES VALEURS FONDAMENTALES CANADIENNES QUE SOULIGNE LA DÉCLARATION DE CALGARY , SOIT QUE LES CANADIENS PARTAGENT AVEC LEUR CONCITOYENS DE LE QUÉBEC LES VALEURS QUE CONSTITUENT LE RESPECT , LE PARTENARIAT , LE ÉQUITÉ , LA JUSTICE ET LE ACCESSIBILITÉ . 
SIXIÈMEMENT , SI TOUTE MODIFICATION CONSTITUTIONNELLE CONFÈRE DE LES POUVOIRS À UNE PROVINCE , CES POUVOIRS DOIVENT ÊTRE ACCORDÉS À TOUTES LES PROVINCES . 
SI LA DÉCLARATION DE CALGARY NE PRÉVOIT PAS DE MODIFICATIONS DE LA DIVISION DE LES POUVOIRS ENTRE LES ORDRES DE GOUVERNEMENT , IL RESTE QUE ELLE PRÉVOIT QUE SI PAREILLE MODIFICATION ÉTAIT ENVISAGÉE , LE PRINCIPE DE LE ÉGALITÉ DE LES PROVINCES DEVRA SE APPLIQUER . 
NOUS CROYONS QUE TOUTES LES PROVINCES DOIVENT DISPOSER DE LES MÊMES OUTILS POUR PROMOUVOIR LEUR PROPRE DÉVELOPPEMENT . 
TOUT OUTIL OFFERT À UNE PROVINCE DOIT RÉPONDRE À LES BESOINS PARTICULIERS DE CELLE - CI ET ÊTRE OFFERT À TOUTES LES AUTRES . 
SEPTIÈMEMENT , UNE PLUS GRANDE COLLABORATION ENTRE LES DEUX ORDRES DE GOUVERNEMENT DANS LE RESPECT DE LES COMPÉTENCES DE CHACUN . 
VOICI CE QUE DIT LE SEPTIÈME PRINCIPE . 
NOUS SOMMES TOUS DE ACCORD POUR DIRE QUE LE IMMENSE MAJORITÉ DE LES CANADIENS VEULENT QUE LEURS GOUVERNEMENTS FÉDÉRAL ET PROVINCIAUX AGISSENT DANS LE INTÉRÊT COMMUN , QUE ILS ÉTABLISSENT UN VRAI PARTENARIAT CANADIEN FONDÉ SUR LA SOLIDARITÉ ET LE RESPECT DE NOTRE DIVERSITÉ AINSI QUE DE LES CHAMPS DE COMPÉTENCE FÉDÉRAUX ET PROVINCIAUX . 
LE GOUVERNEMENT FÉDÉRAL A TRAVAILLÉ TRÈS FORT POUR SE ASSURER DE LE EFFICIENCE ET LE EFFICACITÉ DE LA FÉDÉRATION EN METTANT LE ACCENT SUR LA CONSULTATION ET LA COLLABORATION . 
LA LISTE DE TOUS LES SECTEURS OÙ LES GOUVERNEMENTS FÉDÉRAL ET PROVINCIAUX COLLABORENT EST FORT LONGUE . 
ELLE COMPREND LA FORMATION DE LA MAIN - DE OEUVRE ET LES POURPARLERS FÉDÉRAUX - PROVINCIAUX , POUR NE EN NOMMER QUE DEUX . 
EN CONCLUSION , JE AIMERAIS DIRE QUE LE GOUVERNEMENT FÉDÉRAL RECONNAÎT QUE LE PAYS DANS LEQUEL NOUS VIVONS ÉVOLUE CONSTAMMENT . 
CE EST LÀ UNE RÉALITÉ DE LA COMMUNAUTÉ CANADIENNE . 
CE EST ÉGALEMENT UN FAIT QUE NOUS DEVONS CHANGER , SI NOUS VOULONS SURVIVRE EN TANT QUE SOCIÉTÉ . 
COMME LES DÉPUTÉS PEUVENT LE CONSTATER , LE PROCESSUS DE CONSULTATION ET LES SEPT PRINCIPES ÉNONCÉS À CALGARY SONT DE UNE IMPORTANCE CAPITALE POUR LE UNITÉ DE LE CANADA . 
IL NE Y A RIEN DE PLUS IMPORTANT QUE DE GARDER LE CANADA UNI , ET JE PENSE QUE LA MOTION PRÉSENTÉE AUJOURD' HUI NOUS AIDERA À ATTEINDRE CET OBJECTIF . 
LE CANADA A UNE HISTOIRE REMARQUABLE , SON AVENIR LE SERA ENCORE DAVANTAGE . 
M . JEAN - PAUL MARCHAND ( QUÉBEC - EST , BQ ) : 
MONSIEUR LE PRÉSIDENT , JE AI BIEN AIMÉ LE DISCOURS DE MON COLLÈGUE . 
CE EST BIEN DIT , CE EST TRÈS POLI , MAIS IL NE VEUT RIEN DIRE EN FAIT . 
JE LUI SUGGÈRE , SE IL EN A LE TEMPS , DE LIRE UN LIVRE ÉCRIT PAR UN JOURNALISTE DE LE GLOBE AND MAIL , RAY CONLOGUE , INTITULÉ THE IMPOSSIBLE NATION . 
IL APPRENDRAIT BEAUCOUP SUR LA RÉALITÉ DE LE CANADA , RÉALITÉ QUI EST SYMBOLISÉE JUSTEMENT PAR LA DÉCLARATION DE CALGARY . 
EN 1980 , IL Y A EU UN RÉFÉRENDUM , LE PREMIER RÉFÉRENDUM À LE QUÉBEC , POUR SIGNIFIER À LE CANADA QUE LE QUÉBEC ÉTAIT FRUSTRÉ PAR SA SITUATION À LE CANADA . 
CELA A PRODUIT LE ACCORD DE LE LAC MEECH , LA FORMULE DE LE LAC MEECH SUGGÉRÉE PAR UN GOUVERNEMENT FÉDÉRALISTE À LE QUÉBEC , CELUI DE ROBERT BOURASSA . 
CE ÉTAIT LE MINIMUM DE CE QUE POUVAIT EXIGER LE QUÉBEC DE LE CANADA À CE MOMENT - LÀ . 
ÉVIDEMMENT , CELA A ÉTÉ REFUSÉ PAR LE CANADA , ET PAR LA SUITE , IL Y A EU UN DEUXIÈME RÉFÉRENDUM OÙ LE QUÉBEC A VOTÉ ENCORE PLUS FORT POUR SIGNIFIER SON MALAISE À LE SEIN DE LE CANADA . 
CELA A PRODUIT LA DÉCLARATION DE CALGARY . 
MAIS IL NE Y A ABSOLUMENT RIEN DANS CETTE DÉCLARATION . 
CE EST UNE FORMULE QUI EST EN - DESSOUS DE LA FORMULE DE LE LAC MEECH , DANS LAQUELLE LE SENS MÊME DE LE QUÉBEC COMME CARACTÉRISTIQUE UNIQUE À LE CANADA SE CONFOND AVEC TELLEMENT DE CHOSES QUE ON NE RECONNAÎT PLUS LE QUÉBEC . 
JE ME DEMANDE SI LE DÉPUTÉ POURRAIT ME DIRE DE QUELLE FAÇON LA DÉCLARATION DE CALGARY POURRAIT RÉGLER LE PROBLÈME DE LE UNITÉ ET DE LE ÉGALITÉ À LE CANADA . 
M . LYNN MYERS : 
MONSIEUR LE PRÉSIDENT , JE TROUVE ENCOURAGEANTE LA DÉCLARATION DE CALGARY ET LES VALEURS QUE ELLE DÉFEND , EN PARTICULIER LE PROCESSUS DE CONSULTATION QUI FAIT PARTIE INTÉGRANTE DE CET IMPORTANT COMMUNIQUÉ , FAIT NON SEULEMENT PAR LES PREMIERS MINISTRES MAIS AUSSI PAR LES DIRIGEANTS TERRITORIAUX . 
IL EST IMPORTANT DE SAVOIR QUE LE CANADA PEUT MAINTENANT AGIR EN FONCTION DE CES LIGNES DIRECTRICES ET QUE TOUS LES CANADIENS PUISSENT SUIVRE DE PRÈS UN PROCESSUS DE CONSULTATION ET SE FAIRE ENTENDRE ET QUE NOUS TENTIONS DE UNIR LE PAYS DANS LE RESPECT DE NOTRE HISTOIRE ET DE NOS OBJECTIFS À LE AUBE DE LE XXLE SIÈCLE . 
LE PRÉSIDENT SUPPLÉANT (M. MCCLELLAND ) : 
JE RAPPELLE UNE FOIS ENCORE QUE SE IL Y A PLUS DE UN DÉPUTÉ QUI DÉSIRE RÉPONDRE DURANT LA PÉRIODE DE LES QUESTIONS ET OBSERVATIONS , IL FAUDRAIT SE LIMITER À UNE INTERVENTION DE UNE MINUTE ENVIRON . 
M . KEITH MARTIN ( ESQUIMALT - JUAN DE FUCA , RÉF . ) : 
MONSIEUR LE PRÉSIDENT , JE REMERCIE LE DÉPUTÉ LIBÉRAL DE SON DISCOURS TOUT À FAIT NON - PARTISAN . 
IL A ÉTÉ TRÈS BIEN ACCUEILLI . 
JE VOUDRAIS CEPENDANT LUI POSER UNE QUESTION . 
DEPUIS 15 ANS , DE LES GOUVERNEMENTS SÉPARATISTES PROVINCIAUX TENTENT DE SÉPARER LE QUÉBEC DE LE RESTE DE LE CANADA . 
ÉTANT DONNÉ CE QUE IL A VU SE PRODUIRE À LE CANADA À LE COURS DE LES DIX OU QUINZE DERNIÈRES ANNÉES , LE DÉPUTÉ CROIT - IL QUE LE BLOC QUÉBÉCOIS , M. BOUCHARD ET LE PARTI QUÉBÉCOIS ONT UN QUELCONQUE INTÉRÊT À GARDER LE QUÉBEC À LE INTÉRIEUR DE LE CANADA ? 
M . LYNN MYERS : 
MONSIEUR LE PRÉSIDENT , JE NE OSERAIS JAMAIS PARLER À LA PLACE DE LE PARTI QUÉBÉCOIS OU DE LE BLOC QUÉBÉCOIS , MAIS JE DIS PERSONNELLEMENT QUE JE VOUDRAIS QUE LES CANADIENS , HOMMES ET FEMMES DE BONNE VOLONTÉ DE UN OCÉAN À LE AUTRE , TRAVAILLENT TRÈS FORT POUR ASSURER LA VIABILITÉ ET LE UNITÉ DE CE GRAND PAYS QUI EST LE NÔTRE . 
DE APRÈS MOI , CETTE POSITION DEVRAIT ÊTRE CELLE DE TOUS LES CANADIENS QUI TIENNENT VRAIMENT À LE UNITÉ DE LEUR PAYS ET QUI VEULENT EN FAIRE UN PAYS FORT . 
JE SUIS DE PLUS EN PLUS ENCOURAGÉ EN VOYANT QUE NOUS SOMMES SUR LA BONNE VOIE . JE SUIS SÛR QUE CE EST PRÉCISÉMENT LE ORIENTATION QUE NOUS ALLONS PRENDRE . 
M . KEITH MARTIN ( ESQUIMALT - JUAN DE FUCA , RÉF . ) : 
EN FAIT , EN TANT QUE MEMBRES DE LE PARTI RÉFORMISTE , NOUS SOMMES EN TRAIN DE ESSAYER DE ORGANISER LES CHOSES , DE BRISER LA GLACE SUR LA QUESTION DE LE UNITÉ NATIONALE . 
CETTE QUESTION EST DANS LE AIR DEPUIS PLUS DE 200 ANS , MAIS CE EST SURTOUT DEPUIS LES 15 DERNIÈRES ANNÉES QUE NOUS AVONS VU NOTRE PAYS DIVISÉ EN DEUX SOLITUDES OU EN PLUSIEURS SOLITUDES . 
LES LIENS QUI DEVRAIENT NOUS UNIR ET FAIRE DE NOUS LA PLUS GRANDE NATION DE LE MONDE NE SONT PAS FAVORISÉS . 
ON ENTEND GRONDER LES MARITIMES . 
QUELLE HONTE POUR UN PAYS AUSSI RICHE QUE DE LAISSER CELA SE PRODUIRE . 
SI NOUS CONTINUONS SUR CETTE LANCÉE , CE EST CERTAIN QUE NOUS ALLONS NOUS FRACTIONNER . 
NE SERAIT - CE PAS UNE GRANDE TRAGÉDIE ? 
NE SERAIT - CE PAS TRAGIQUE POUR NOUS DE NOUS FRACTIONNER EN PETITES SOLITUDES , DE NOUS LIMITER À NOS PETITS MONDES , ALORS QUE NOUS POUVONS ALLER BEAUCOUP PLUS LOIN EN TANT QUE GROUPE QUE SÉPARÉMENT ? 
CELA NE A JAMAIS ÉTÉ AUSSI ÉVIDENT QUE À LE RÉFÉRENDUM DE 1995 . 
CE NE EST PAS SIMPLEMENT APPARU À LA TÉLÉVISION UN SOIR . 
CE ÉTAIT PLUTÔT LE POINT CULMINANT DE UNE PÉRIODE DE À LE MOINS 15 ANS DE MÉCONTENTEMENT PROFOND DE LA PART DE LES GENS DE LE QUÉBEC , MAIS AUSSI DE LES GENS DE UN BOUT À LE AUTRE DE LE PAYS . 
LES QUÉBÉCOIS EXPRIMENT PEUT - ÊTRE LEUR MÉCONTENTEMENT DE FAÇON DIFFÉRENTE , MAIS LES AUTRES CANADIENS EXPRIMENT LE LEUR TOUT AUSSI PASSIONNÉMENT . 
NOUS TROUVONS QUE LE CADRE CONSTITUTIONNEL DANS LEQUEL NOTRE PAYS EXISTE NE FONCTIONNE PAS . 
LA PREUVE EST LÀ . 
À LE QUÉBEC , EN COLOMBIE - BRITANNIQUE ET DANS LE RESTE DE LE PAYS , LES GENS RÉCLAMENT UNE VISION NOUVELLE DE LE CANADA , UN CANADA NOUVEAU DANS LEQUEL LES PROVINCES AURAIENT LES POUVOIRS NÉCESSAIRES POUR FAIRE CE QUE ELLES FONT LE MIEUX ET LE FÉDÉRAL CE QUE IL FAIT LE MIEUX , UN CANADA DANS LEQUEL LES CITOYENS AURAIENT UNE INFLUENCE DIRECTE SUR LE ÉLABORATION DE LES POLITIQUES ADOPTÉES PAR LA CHAMBRE . 
CE QUI SE PASSE DANS CETTE CHAMBRE , CE NE EST PAS DE LA DÉMOCRATIE , COMME NOUS LE SAVONS TOUS . 
NOS CONCITOYENS SE SENTENT ÉTRANGERS À LES ORIENTATIONS QUI SONT PRISES PAR LA CHAMBRE DE LES COMMUNES . 
SUPPOSONS QUE LES CHOSES CONTINUENT À ÉVOLUER DE LA MÊME FAÇON ET QUE LA SÉPARATION CONTINUE À PERDRE DE SON ATTRAIT , SI À LE PROCHAIN RÉFÉRENDUM LES GENS VOTENT NON À 60P. 100 , EST - CE QUE CE SERAIT UN SUCCÈS ? 
JE PRÉTENDS QUE CE NE SERAIT PAS UN SUCCÈS . 
